graph TD
    ActEvidenceValidator_validate["ActEvidenceValidator.validate"]
    BoardRenderer___init__["BoardRenderer.__init__"]
    BoardRenderer_check["BoardRenderer.check"]
    BoardRenderer_render["BoardRenderer.render"]
    BuiltinGraphProvider_health["BuiltinGraphProvider.health"]
    BuiltinGraphProvider_query["BuiltinGraphProvider.query"]
    BuiltinGraphProvider_sync["BuiltinGraphProvider.sync"]
    ClassicDeployer_deploy["ClassicDeployer.deploy"]
    CodegraphProvider__query_sqlite["CodegraphProvider._query_sqlite"]
    CodegraphProvider__run["CodegraphProvider._run"]
    CodegraphProvider__sync_lock["CodegraphProvider._sync_lock"]
    CodegraphProvider_health["CodegraphProvider.health"]
    CodegraphProvider_query["CodegraphProvider.query"]
    CodegraphProvider_sync["CodegraphProvider.sync"]
    ContinuationEngine__bind_lock["ContinuationEngine._bind_lock"]
    ContinuationEngine__emit_run_events["ContinuationEngine._emit_run_events"]
    ContinuationEngine__find["ContinuationEngine._find"]
    ContinuationEngine__host_binding_path["ContinuationEngine._host_binding_path"]
    ContinuationEngine__host_reference["ContinuationEngine._host_reference"]
    ContinuationEngine__host_resolution["ContinuationEngine._host_resolution"]
    ContinuationEngine__legacy_finish_guard["ContinuationEngine._legacy_finish_guard"]
    ContinuationEngine__run_lock["ContinuationEngine._run_lock"]
    ContinuationEngine__validate_run_id["ContinuationEngine._validate_run_id"]
    ContinuationEngine_bind_host_session["ContinuationEngine.bind_host_session"]
    ContinuationEngine_bind_story["ContinuationEngine.bind_story"]
    ContinuationEngine_checkpoint["ContinuationEngine.checkpoint"]
    ContinuationEngine_definition["ContinuationEngine.definition"]
    ContinuationEngine_finish_guard["ContinuationEngine.finish_guard"]
    ContinuationEngine_path_for["ContinuationEngine.path_for"]
    ContinuationEngine_read["ContinuationEngine.read"]
    ContinuationEngine_resolve_host_run["ContinuationEngine.resolve_host_run"]
    ContinuationEngine_resume["ContinuationEngine.resume"]
    ContinuationEngine_revalidate_artifacts["ContinuationEngine.revalidate_artifacts"]
    ContinuationEngine_start["ContinuationEngine.start"]
    ContinuationEngine_validate_managed_operation["ContinuationEngine.validate_managed_operation"]
    ContinuationStore__active_peer_story_ids["ContinuationStore._active_peer_story_ids"]
    ContinuationStore__ambiguous_generic_act_result["ContinuationStore._ambiguous_generic_act_result"]
    ContinuationStore__archive_completed["ContinuationStore._archive_completed"]
    ContinuationStore__checkpoint_locked["ContinuationStore._checkpoint_locked"]
    ContinuationStore__emit_checkpoint_events["ContinuationStore._emit_checkpoint_events"]
    ContinuationStore__fingerprints["ContinuationStore._fingerprints"]
    ContinuationStore__generic_act_resolution["ContinuationStore._generic_act_resolution"]
    ContinuationStore__paths["ContinuationStore._paths"]
    ContinuationStore__require_valid_spec["ContinuationStore._require_valid_spec"]
    ContinuationStore__stale_reasons["ContinuationStore._stale_reasons"]
    ContinuationStore__story_fact_path["ContinuationStore._story_fact_path"]
    ContinuationStore__story_lock["ContinuationStore._story_lock"]
    ContinuationStore__validate_completion["ContinuationStore._validate_completion"]
    ContinuationStore__validate_step_evidence["ContinuationStore._validate_step_evidence"]
    ContinuationStore__validate_story_id["ContinuationStore._validate_story_id"]
    ContinuationStore_checkpoint["ContinuationStore.checkpoint"]
    ContinuationStore_deny["ContinuationStore.deny"]
    ContinuationStore_diagnostics["ContinuationStore.diagnostics"]
    ContinuationStore_legacy_handoff["ContinuationStore.legacy_handoff"]
    ContinuationStore_path_for["ContinuationStore.path_for"]
    ContinuationStore_read["ContinuationStore.read"]
    ContinuationStore_resume["ContinuationStore.resume"]
    ContinuationStore_status["ContinuationStore.status"]
    DeployIntegrityError___init__["DeployIntegrityError.__init__"]
    DeployerBase_deploy_agents["DeployerBase.deploy_agents"]
    DeployerBase_deploy_ci["DeployerBase.deploy_ci"]
    DeployerBase_deploy_commands["DeployerBase.deploy_commands"]
    DeployerBase_deploy_guides["DeployerBase.deploy_guides"]
    DeployerBase_deploy_rules["DeployerBase.deploy_rules"]
    DeployerBase_deploy_skills["DeployerBase.deploy_skills"]
    DeployerBase_render_prompt["DeployerBase.render_prompt"]
    DeployerBase_strip_excluded_command_references["DeployerBase.strip_excluded_command_references"]
    DeployerBase_validate_deployed_content["DeployerBase.validate_deployed_content"]
    EvidenceReceipt_for_files["EvidenceReceipt.for_files"]
    GovernanceMigrator__legacy_lessons["GovernanceMigrator._legacy_lessons"]
    GovernanceMigrator__legacy_stories["GovernanceMigrator._legacy_stories"]
    GovernanceMigrator__remove_installed["GovernanceMigrator._remove_installed"]
    GovernanceMigrator_migrate["GovernanceMigrator.migrate"]
    GraphProviderError___init__["GraphProviderError.__init__"]
    GraphProviderRouter__query_one["GraphProviderRouter._query_one"]
    GraphProviderRouter_query["GraphProviderRouter.query"]
    GraphQueryResult_to_dict["GraphQueryResult.to_dict"]
    HostCapabilities_auto_resume_available["HostCapabilities.auto_resume_available"]
    HostContinuationRunner__after_legacy_turn["HostContinuationRunner._after_legacy_turn"]
    HostContinuationRunner__digest["HostContinuationRunner._digest"]
    HostContinuationRunner__session_reference["HostContinuationRunner._session_reference"]
    HostContinuationRunner_after_model_turn["HostContinuationRunner.after_model_turn"]
    HostContinuationRunner_before_operation["HostContinuationRunner.before_operation"]
    HostContinuationRunner_record_resume_failure["HostContinuationRunner.record_resume_failure"]
    LessonRepository__load["LessonRepository._load"]
    LessonRepository_add["LessonRepository.add"]
    LessonRepository_import_legacy["LessonRepository.import_legacy"]
    LessonRepository_recent["LessonRepository.recent"]
    NoopValidator__require_graph_evidence["NoopValidator._require_graph_evidence"]
    NoopValidator_fingerprints["NoopValidator.fingerprints"]
    NoopValidator_revalidate_artifacts["NoopValidator.revalidate_artifacts"]
    NoopValidator_validate["NoopValidator.validate"]
    PlanEvidenceValidator__board["PlanEvidenceValidator._board"]
    PlanEvidenceValidator__require_acceptance["PlanEvidenceValidator._require_acceptance"]
    PlanEvidenceValidator__require_board["PlanEvidenceValidator._require_board"]
    PlanEvidenceValidator__require_complete["PlanEvidenceValidator._require_complete"]
    PlanEvidenceValidator__require_lint["PlanEvidenceValidator._require_lint"]
    PlanEvidenceValidator__require_requirements["PlanEvidenceValidator._require_requirements"]
    PlanEvidenceValidator__require_security["PlanEvidenceValidator._require_security"]
    PlanEvidenceValidator__spec["PlanEvidenceValidator._spec"]
    PlanEvidenceValidator__text["PlanEvidenceValidator._text"]
    PlanEvidenceValidator_fingerprints["PlanEvidenceValidator.fingerprints"]
    PlanEvidenceValidator_revalidate_artifacts["PlanEvidenceValidator.revalidate_artifacts"]
    PlanEvidenceValidator_validate["PlanEvidenceValidator.validate"]
    PlanFinalizer__journal_path["PlanFinalizer._journal_path"]
    PlanFinalizer__projection_lock["PlanFinalizer._projection_lock"]
    PlanFinalizer__save_journal["PlanFinalizer._save_journal"]
    PlanFinalizer__story_lock["PlanFinalizer._story_lock"]
    PlanFinalizer__validate_journal["PlanFinalizer._validate_journal"]
    PlanFinalizer__write_board["PlanFinalizer._write_board"]
    PlanFinalizer__write_context["PlanFinalizer._write_context"]
    PlanFinalizer_finalize["PlanFinalizer.finalize"]
    PluginDeployer_deploy["PluginDeployer.deploy"]
    ProjectCommandValidator_validate["ProjectCommandValidator.validate"]
    StoryRepository__authorize["StoryRepository._authorize"]
    StoryRepository__validate["StoryRepository._validate"]
    StoryRepository__write["StoryRepository._write"]
    StoryRepository_add["StoryRepository.add"]
    StoryRepository_add_task["StoryRepository.add_task"]
    StoryRepository_complete_task["StoryRepository.complete_task"]
    StoryRepository_list["StoryRepository.list"]
    StoryRepository_load["StoryRepository.load"]
    StoryRepository_move["StoryRepository.move"]
    StoryRepository_path_for["StoryRepository.path_for"]
    TextSearchProvider_health["TextSearchProvider.health"]
    TextSearchProvider_query["TextSearchProvider.query"]
    TextSearchProvider_sync["TextSearchProvider.sync"]
    WorkflowEngine__active_runs_for_story["WorkflowEngine._active_runs_for_story"]
    WorkflowEngine__complete_locked["WorkflowEngine._complete_locked"]
    WorkflowEngine__completed_run_for_story["WorkflowEngine._completed_run_for_story"]
    WorkflowEngine__find_run_for_unit["WorkflowEngine._find_run_for_unit"]
    WorkflowEngine__idempotent_run_result["WorkflowEngine._idempotent_run_result"]
    WorkflowEngine__idempotent_submission_result["WorkflowEngine._idempotent_submission_result"]
    WorkflowEngine__idempotent_unit_result["WorkflowEngine._idempotent_unit_result"]
    WorkflowEngine__lock["WorkflowEngine._lock"]
    WorkflowEngine__read["WorkflowEngine._read"]
    WorkflowEngine__read_scanned_state["WorkflowEngine._read_scanned_state"]
    WorkflowEngine__run["WorkflowEngine._run"]
    WorkflowEngine__scan_or_skip["WorkflowEngine._scan_or_skip"]
    WorkflowEngine__start["WorkflowEngine._start"]
    WorkflowEngine__story_lock["WorkflowEngine._story_lock"]
    WorkflowEngine__template["WorkflowEngine._template"]
    WorkflowEngine__unit["WorkflowEngine._unit"]
    WorkflowEngine__validate_completed_finalize_journal["WorkflowEngine._validate_completed_finalize_journal"]
    WorkflowEngine__validate_receipt["WorkflowEngine._validate_receipt"]
    WorkflowEngine__write["WorkflowEngine._write"]
    WorkflowEngine_acquire["WorkflowEngine.acquire"]
    WorkflowEngine_bind_story["WorkflowEngine.bind_story"]
    WorkflowEngine_expire["WorkflowEngine.expire"]
    WorkflowEngine_import_legacy["WorkflowEngine.import_legacy"]
    WorkflowEngine_lease_current["WorkflowEngine.lease_current"]
    WorkflowEngine_path_for["WorkflowEngine.path_for"]
    WorkflowEngine_plan_ready_to_finalize["WorkflowEngine.plan_ready_to_finalize"]
    WorkflowEngine_record_turn_terminal["WorkflowEngine.record_turn_terminal"]
    WorkflowEngine_reject["WorkflowEngine.reject"]
    WorkflowEngine_renew["WorkflowEngine.renew"]
    WorkflowEngine_resume["WorkflowEngine.resume"]
    WorkflowEngine_retry["WorkflowEngine.retry"]
    WorkflowEngine_start["WorkflowEngine.start"]
    WorkflowEngine_status["WorkflowEngine.status"]
    WorkflowEngine_submit["WorkflowEngine.submit"]
    WorkflowEngine_workflow_ready_to_finalize["WorkflowEngine.workflow_ready_to_finalize"]
    WorkflowFinalizer__complete_act_story_tasks["WorkflowFinalizer._complete_act_story_tasks"]
    WorkflowFinalizer__completion_evidence["WorkflowFinalizer._completion_evidence"]
    WorkflowFinalizer__journal_path["WorkflowFinalizer._journal_path"]
    WorkflowFinalizer__save["WorkflowFinalizer._save"]
    WorkflowFinalizer__validate_act_story_projection["WorkflowFinalizer._validate_act_story_projection"]
    WorkflowFinalizer__validate_completion["WorkflowFinalizer._validate_completion"]
    WorkflowFinalizer__validate_pdca_completion["WorkflowFinalizer._validate_pdca_completion"]
    WorkflowFinalizer_finalize["WorkflowFinalizer.finalize"]
    __module__["__module__"]
    _add_fix_flag["_add_fix_flag"]
    _all_config_dirs["_all_config_dirs"]
    _append_host_warnings["_append_host_warnings"]
    _archived["_archived"]
    _attempt_metadata["_attempt_metadata"]
    _board_block["_board_block"]
    _build_claude_md_managed_content["_build_claude_md_managed_content"]
    _build_command_rules_header["_build_command_rules_header"]
    _build_github_workflow["_build_github_workflow"]
    _build_gitlab_ci["_build_gitlab_ci"]
    _build_rule_id_to_filename["_build_rule_id_to_filename"]
    _build_rule_id_to_key["_build_rule_id_to_key"]
    _bypassed["_bypassed"]
    _changed_source_files["_changed_source_files"]
    _check_adapter_compat["_check_adapter_compat"]
    _check_code_smells["_check_code_smells"]
    _check_completion["_check_completion"]
    _check_dependency_health["_check_dependency_health"]
    _check_docstring_coverage["_check_docstring_coverage"]
    _check_gh_available["_check_gh_available"]
    _check_h1["_check_h1"]
    _check_h2["_check_h2"]
    _check_h3["_check_h3"]
    _check_h4["_check_h4"]
    _check_h5["_check_h5"]
    _check_h6["_check_h6"]
    _check_h7["_check_h7"]
    _check_lexical_integrity["_check_lexical_integrity"]
    _check_semantic_integrity["_check_semantic_integrity"]
    _check_spec_path["_check_spec_path"]
    _check_test_coverage["_check_test_coverage"]
    _checkpoint_continuation["_checkpoint_continuation"]
    _classify_coverage["_classify_coverage"]
    _clean["_clean"]
    _cleanup_legacy["_cleanup_legacy"]
    _cleanup_legacy_portable_methods["_cleanup_legacy_portable_methods"]
    _codex_cli_version["_codex_cli_version"]
    _codex_hook_present["_codex_hook_present"]
    _collect_findings["_collect_findings"]
    _collect_insights["_collect_insights"]
    _collect_insights__dfs["_collect_insights._dfs"]
    _collect_signals["_collect_signals"]
    _command_root["_command_root"]
    _compute_hotspots["_compute_hotspots"]
    _compute_layer_level["_compute_layer_level"]
    _compute_score["_compute_score"]
    _convert_command_frontmatter_opencode["_convert_command_frontmatter_opencode"]
    _counter_path["_counter_path"]
    _create_issue["_create_issue"]
    _debug_completion["_debug_completion"]
    _dedupe_scope["_dedupe_scope"]
    _deploy_agents["_deploy_agents"]
    _deploy_ci["_deploy_ci"]
    _deploy_classic["_deploy_classic"]
    _deploy_claude_md["_deploy_claude_md"]
    _deploy_claude_md_inline["_deploy_claude_md_inline"]
    _deploy_commands["_deploy_commands"]
    _deploy_guides["_deploy_guides"]
    _deploy_marketplace["_deploy_marketplace"]
    _deploy_marketplace_json["_deploy_marketplace_json"]
    _deploy_plugin["_deploy_plugin"]
    _deploy_plugin_json["_deploy_plugin_json"]
    _deploy_rules["_deploy_rules"]
    _deploy_skills["_deploy_skills"]
    _detect_ghe["_detect_ghe"]
    _detect_platform["_detect_platform"]
    _detect_sources["_detect_sources"]
    _discover_references["_discover_references"]
    _done_completion["_done_completion"]
    _enforce_deploy_integrity["_enforce_deploy_integrity"]
    _enforcement_settings["_enforcement_settings"]
    _ensure_entry_point_deployers["_ensure_entry_point_deployers"]
    _extract["_extract"]
    _extract_module_path["_extract_module_path"]
    _extract_sprint_contract["_extract_sprint_contract"]
    _finalize_request_digest["_finalize_request_digest"]
    _find_existing_spec["_find_existing_spec"]
    _fingerprint["_fingerprint"]
    _flatten_pip_audit_vulns["_flatten_pip_audit_vulns"]
    _fmt_scalar["_fmt_scalar"]
    _generate_claude_local_md_if_missing["_generate_claude_local_md_if_missing"]
    _generate_config_if_missing["_generate_config_if_missing"]
    _generate_continuation["_generate_continuation"]
    _generate_project_claude_md["_generate_project_claude_md"]
    _generate_suggested_tasks["_generate_suggested_tasks"]
    _generic_finalize_request_digest["_generic_finalize_request_digest"]
    _get_command_rules["_get_command_rules"]
    _get_done_ids["_get_done_ids"]
    _get_git_branches["_get_git_branches"]
    _get_global_version_marker["_get_global_version_marker"]
    _get_issue_tracker_provider["_get_issue_tracker_provider"]
    _get_last_n_entries["_get_last_n_entries"]
    _git["_git"]
    _git_head["_git_head"]
    _has_dir_with_files["_has_dir_with_files"]
    _has_production_caller["_has_production_caller"]
    _hash["_hash"]
    _hooks_json_lock["_hooks_json_lock"]
    _hotfix_completion["_hotfix_completion"]
    _insert_after_frontmatter["_insert_after_frontmatter"]
    _inside["_inside"]
    _inside_protected["_inside_protected"]
    _install_argv["_install_argv"]
    _is_doc_only["_is_doc_only"]
    _is_docs_only["_is_docs_only"]
    _is_docs_or_tests_only["_is_docs_or_tests_only"]
    _is_duplicate["_is_duplicate"]
    _is_fully_protected["_is_fully_protected"]
    _is_initialized["_is_initialized"]
    _is_json_value["_is_json_value"]
    _is_pactkit_managed_global_md["_is_pactkit_managed_global_md"]
    _is_specific["_is_specific"]
    _is_user_modified_claude_md["_is_user_modified_claude_md"]
    _is_version_file["_is_version_file"]
    _jaccard_similarity["_jaccard_similarity"]
    _load_entry_point_deployers["_load_entry_point_deployers"]
    _load_touches["_load_touches"]
    _load_write_scope["_load_write_scope"]
    _major_minor["_major_minor"]
    _max_nesting_depth["_max_nesting_depth"]
    _merge["_merge"]
    _merge_event_entry["_merge_event_entry"]
    _merge_pre_tooluse_entry["_merge_pre_tooluse_entry"]
    _migrate_from_scafpy["_migrate_from_scafpy"]
    _minimal_paths["_minimal_paths"]
    _module_available["_module_available"]
    _new_public_symbols["_new_public_symbols"]
    _no_external_enabled["_no_external_enabled"]
    _no_git_enabled["_no_git_enabled"]
    _nonempty["_nonempty"]
    _normalize_write_scope["_normalize_write_scope"]
    _now["_now"]
    _opaque_ref["_opaque_ref"]
    _parse_ac_to_reqs["_parse_ac_to_reqs"]
    _parse_active_stories["_parse_active_stories"]
    _parse_board["_parse_board"]
    _parse_coverage_output["_parse_coverage_output"]
    _parse_field_table["_parse_field_table"]
    _parse_item_type["_parse_item_type"]
    _parse_last_lessons["_parse_last_lessons"]
    _parse_recent_completions["_parse_recent_completions"]
    _parse_requirements["_parse_requirements"]
    _parse_table["_parse_table"]
    _parse_touches["_parse_touches"]
    _parse_ts["_parse_ts"]
    _parse_version["_parse_version"]
    _pass["_pass"]
    _path_ends_with_ext["_path_ends_with_ext"]
    _path_matches_any["_path_matches_any"]
    _paths_overlap["_paths_overlap"]
    _persisted_fingerprints["_persisted_fingerprints"]
    _pr_completion["_pr_completion"]
    _print_codegraph_sync["_print_codegraph_sync"]
    _print_mcp_recommendations["_print_mcp_recommendations"]
    _probe_flag_gate["_probe_flag_gate"]
    _probe_flag_gate__probe["_probe_flag_gate._probe"]
    _project_deploy_dirs["_project_deploy_dirs"]
    _project_host_guarantees["_project_host_guarantees"]
    _propose_claude_md_candidate["_propose_claude_md_candidate"]
    _pytest_command["_pytest_command"]
    _pytest_interpreter["_pytest_interpreter"]
    _python_files["_python_files"]
    _python_interface["_python_interface"]
    _read["_read"]
    _read_content["_read_content"]
    _read_manifest["_read_manifest"]
    _receipt_digest["_receipt_digest"]
    _receipt_dir["_receipt_dir"]
    _receipt_execution_mode["_receipt_execution_mode"]
    _receipt_exists["_receipt_exists"]
    _receipt_shape_reason["_receipt_shape_reason"]
    _record["_record"]
    _record_gate["_record_gate"]
    _record_story_id["_record_story_id"]
    _refresh["_refresh"]
    _refspec_target["_refspec_target"]
    _release_completion["_release_completion"]
    _relpath["_relpath"]
    _remove_path["_remove_path"]
    _removes_gate_entry["_removes_gate_entry"]
    _render_prompt["_render_prompt"]
    _render_skill_md["_render_skill_md"]
    _render_stack_line["_render_stack_line"]
    _render_value["_render_value"]
    _repair_table_structure["_repair_table_structure"]
    _resolve_scope["_resolve_scope"]
    _rewrite_skills_prefix["_rewrite_skills_prefix"]
    _rewrite_yaml["_rewrite_yaml"]
    _rotate_if_needed["_rotate_if_needed"]
    _run_deploy_command["_run_deploy_command"]
    _run_layer["_run_layer"]
    _run_pytest_cov["_run_pytest_cov"]
    _safe_repo_path["_safe_repo_path"]
    _sanitize["_sanitize"]
    _sanitize_evidence["_sanitize_evidence"]
    _sanitize_text["_sanitize_text"]
    _scaffold_audit_spec["_scaffold_audit_spec"]
    _schema_command["_schema_command"]
    _search_issue["_search_issue"]
    _section["_section"]
    _sha256["_sha256"]
    _should_refresh_audit["_should_refresh_audit"]
    _spec_edit_allowed["_spec_edit_allowed"]
    _spec_status["_spec_status"]
    _sprint_completion["_sprint_completion"]
    _status_path["_status_path"]
    _story_fact_block["_story_fact_block"]
    _strip_code_spans["_strip_code_spans"]
    _suggest_action["_suggest_action"]
    _summarize["_summarize"]
    _task_id["_task_id"]
    _terminal["_terminal"]
    _tests_pass["_tests_pass"]
    _timestamp["_timestamp"]
    _token_valid["_token_valid"]
    _tool_version["_tool_version"]
    _unavailable["_unavailable"]
    _unit["_unit"]
    _update_stack_if_stale["_update_stack_if_stale"]
    _upsert_claude_md_managed_block["_upsert_claude_md_managed_block"]
    _upsert_venv_managed_block["_upsert_venv_managed_block"]
    _validate_attempt_record["_validate_attempt_record"]
    _validate_developer["_validate_developer"]
    _validate_finalize_projection_fingerprints["_validate_finalize_projection_fingerprints"]
    _validate_finalize_projection_fingerprints_normalize_timestamp["_validate_finalize_projection_fingerprints.normalize_timestamp"]
    _validate_fingerprint_map["_validate_fingerprint_map"]
    _validate_idempotency_record["_validate_idempotency_record"]
    _validate_identity["_validate_identity"]
    _validate_item_id["_validate_item_id"]
    _validate_native_workflow_topology["_validate_native_workflow_topology"]
    _validate_run_id["_validate_run_id"]
    _validate_story_id["_validate_story_id"]
    _validate_unit_id["_validate_unit_id"]
    _validate_work_unit_record["_validate_work_unit_record"]
    _validate_work_unit_snapshot["_validate_work_unit_snapshot"]
    _validate_workflow_start["_validate_workflow_start"]
    _validate_workflow_state["_validate_workflow_state"]
    _worktree_fingerprint["_worktree_fingerprint"]
    _write_audit_json["_write_audit_json"]
    activate_pactkit_maintainer_overlay["activate_pactkit_maintainer_overlay"]
    active_story_id["active_story_id"]
    append_event["append_event"]
    append_lesson["append_lesson"]
    assess["assess"]
    atomic_write["atomic_write"]
    audit["audit"]
    authorization_path["authorization_path"]
    authorize["authorize"]
    auto_merge_config_file["auto_merge_config_file"]
    build_change_risk_profile["build_change_risk_profile"]
    build_report["build_report"]
    check_adapter_compat["check_adapter_compat"]
    check_adapter_skew["check_adapter_skew"]
    check_archive_honesty["check_archive_honesty"]
    check_bash_command["check_bash_command"]
    check_codex_execution_capability["check_codex_execution_capability"]
    check_codex_hook_capability["check_codex_hook_capability"]
    check_command["check_command"]
    check_config_completeness["check_config_completeness"]
    check_config_copy_drift["check_config_copy_drift"]
    check_config_drift["check_config_drift"]
    check_config_drift__dir_or_file_in_any["check_config_drift._dir_or_file_in_any"]
    check_config_drift__exists_in_any["check_config_drift._exists_in_any"]
    check_core_metadata_divergence["check_core_metadata_divergence"]
    check_coverage["check_coverage"]
    check_dead_imports["check_dead_imports"]
    check_deploy_parity["check_deploy_parity"]
    check_deps["check_deps"]
    check_edit_tool["check_edit_tool"]
    check_graph_provider["check_graph_provider"]
    check_hld_module_count["check_hld_module_count"]
    check_init_markers["check_init_markers"]
    check_legacy_engine_usage["check_legacy_engine_usage"]
    check_orphaned_specs["check_orphaned_specs"]
    check_pattern_duplication["check_pattern_duplication"]
    check_push["check_push"]
    check_requirement_evidence["check_requirement_evidence"]
    check_requirement_evidence__mentioned["check_requirement_evidence._mentioned"]
    check_rule_ownership["check_rule_ownership"]
    check_stale_docs["check_stale_docs"]
    check_stale_graphs["check_stale_graphs"]
    check_status_consistency["check_status_consistency"]
    check_version_mismatch["check_version_mismatch"]
    check_wiring["check_wiring"]
    check_workflow_continuation["check_workflow_continuation"]
    classify_changes["classify_changes"]
    classify_signals["classify_signals"]
    clean_artifacts["clean_artifacts"]
    cleanup_disabled_command_skills["cleanup_disabled_command_skills"]
    cleanup_unmodified_legacy_skills["cleanup_unmodified_legacy_skills"]
    codegraph_sync["codegraph_sync"]
    collect_changed_files["collect_changed_files"]
    collect_gate_telemetry["collect_gate_telemetry"]
    collect_runs["collect_runs"]
    compute_conflicts["compute_conflicts"]
    compute_waves["compute_waves"]
    context_output_path["context_output_path"]
    current_branch["current_branch"]
    decide_test_set["decide_test_set"]
    deploy["deploy"]
    detect_security_scope["detect_security_scope"]
    detect_security_scope__any_content_matches["detect_security_scope._any_content_matches"]
    detect_stack["detect_stack"]
    detect_stacks["detect_stacks"]
    detect_venv["detect_venv"]
    ensure_gate_channel["ensure_gate_channel"]
    evaluate_agent_final["evaluate_agent_final"]
    existing_config_copies["existing_config_copies"]
    expected_components["expected_components"]
    find_pactkit_yaml["find_pactkit_yaml"]
    format_markdown_table["format_markdown_table"]
    gate_channel["gate_channel"]
    gate_events_path["gate_events_path"]
    generate_context["generate_context"]
    generate_default_yaml["generate_default_yaml"]
    generate_item_id["generate_item_id"]
    get_default_config["get_default_config"]
    get_deployable_commands["get_deployable_commands"]
    get_portable_methods["get_portable_methods"]
    get_profile["get_profile"]
    get_skill_manifest["get_skill_manifest"]
    get_workflow["get_workflow"]
    hook_entry["hook_entry"]
    install_codex_hook["install_codex_hook"]
    install_deps["install_deps"]
    install_git_hook["install_git_hook"]
    install_hook["install_hook"]
    install_pre_push_hook["install_pre_push_hook"]
    is_environment_format["is_environment_format"]
    is_pactkit_self_development_root["is_pactkit_self_development_root"]
    issue_sync["issue_sync"]
    json_report["json_report"]
    lint_context["lint_context"]
    lint_lessons["lint_lessons"]
    lint_testcase["lint_testcase"]
    load_config["load_config"]
    load_previous_hashes["load_previous_hashes"]
    load_previous_manifest["load_previous_manifest"]
    load_story_graph["load_story_graph"]
    main["main"]
    main__add_deploy_args["main._add_deploy_args"]
    main__unit_json["main._unit_json"]
    main__workflow_evidence["main._workflow_evidence"]
    map_to_tests["map_to_tests"]
    match_scope["match_scope"]
    normalize_rule_id["normalize_rule_id"]
    pactkit_owned_files["pactkit_owned_files"]
    pactkit_rule_ownership["pactkit_rule_ownership"]
    parse_junit_counts["parse_junit_counts"]
    parse_pytest_summary["parse_pytest_summary"]
    parse_story["parse_story"]
    pid_alive["pid_alive"]
    pre_compact_entry["pre_compact_entry"]
    preserve_or_write["preserve_or_write"]
    probe_commit_gate["probe_commit_gate"]
    probe_coverage_gate["probe_coverage_gate"]
    probe_push_gate["probe_push_gate"]
    probe_tamper_guard["probe_tamper_guard"]
    project_command_validator["project_command_validator"]
    project_router["project_router"]
    pytest_command["pytest_command"]
    read_events["read_events"]
    read_legacy_usage["read_legacy_usage"]
    read_status["read_status"]
    record_attempt["record_attempt"]
    record_deployed_command["record_deployed_command"]
    record_gate_event["record_gate_event"]
    record_legacy_usage["record_legacy_usage"]
    record_status["record_status"]
    redact_command["redact_command"]
    refresh_test_count["refresh_test_count"]
    register_deployer["register_deployer"]
    render["render"]
    render_check_report["render_check_report"]
    render_config_yaml["render_config_yaml"]
    render_mermaid["render_mermaid"]
    render_report["render_report"]
    render_summary["render_summary"]
    resolve_pactkit_yaml_dir["resolve_pactkit_yaml_dir"]
    resolve_project_root["resolve_project_root"]
    resolve_push_target["resolve_push_target"]
    resolve_rule_context["resolve_rule_context"]
    resolve_scope["resolve_scope"]
    retire_disabled_agents["retire_disabled_agents"]
    retire_disabled_skills["retire_disabled_skills"]
    rollback_paths["rollback_paths"]
    run_events_path["run_events_path"]
    run_garden["run_garden"]
    run_gate["run_gate"]
    run_lint["run_lint"]
    run_observe["run_observe"]
    run_pytest["run_pytest"]
    run_spec_preflight["run_spec_preflight"]
    run_visualize_graphs["run_visualize_graphs"]
    run_visualize_single["run_visualize_single"]
    scan_and_replace_tbd["scan_and_replace_tbd"]
    scan_command["scan_command"]
    schema_config_report["schema_config_report"]
    scrub_enforcement_records["scrub_enforcement_records"]
    select_execution_mode["select_execution_mode"]
    session_start_entry["session_start_entry"]
    sha256_file["sha256_file"]
    should_visualize["should_visualize"]
    stack_test_command["stack_test_command"]
    story_events_path["story_events_path"]
    sync_config_copies["sync_config_copies"]
    to_json["to_json"]
    update_spec_status["update_spec_status"]
    update_yaml_stack["update_yaml_stack"]
    validate_config["validate_config"]
    validate_registry["validate_registry"]
    validate_skill_recovery_contracts["validate_skill_recovery_contracts"]
    verification_outcome_unknown["verification_outcome_unknown"]
    verify_story["verify_story"]
    write_command_manifest["write_command_manifest"]
    write_deploy_manifest["write_deploy_manifest"]
    check_deps --> _detect_platform
    check_deps --> _install_argv
    check_deps --> _tool_version
    _no_external_enabled --> load_config
    install_deps --> _no_external_enabled
    install_deps --> _detect_platform
    install_deps --> _install_argv
    install_deps --> check_deps
    _section --> ContinuationEngine_start
    _parse_table --> _section
    _discover_references --> _parse_table
    _discover_references --> LessonRepository_add
    _discover_references --> _inside
    _extract --> ContinuationEngine_start
    _extract --> _python_interface
    run_spec_preflight --> _discover_references
    run_spec_preflight --> atomic_write
    run_spec_preflight --> atomic_write
    run_spec_preflight --> _inside
    run_spec_preflight --> _sha256
    run_spec_preflight --> _receipt_dir
    run_spec_preflight --> _receipt_dir
    run_spec_preflight --> _inside
    run_spec_preflight --> _extract
    run_spec_preflight --> _sha256
    run_spec_preflight --> _sha256
    classify_changes --> _is_doc_only
    classify_changes --> _is_version_file
    _refresh --> generate_context
    _refresh --> atomic_write
    _refresh --> context_output_path
    session_start_entry --> _refresh
    pre_compact_entry --> _refresh
    activate_pactkit_maintainer_overlay --> is_pactkit_self_development_root
    find_pactkit_yaml --> ContinuationEngine_start
    resolve_pactkit_yaml_dir --> is_environment_format
    resolve_pactkit_yaml_dir --> get_profile
    resolve_pactkit_yaml_dir --> get_profile
    sync_config_copies --> existing_config_copies
    sync_config_copies --> atomic_write
    check_config_copy_drift --> existing_config_copies
    load_config --> get_default_config
    load_config --> _validate_developer
    load_config --> find_pactkit_yaml
    load_config --> get_default_config
    auto_merge_config_file --> _rewrite_yaml
    update_yaml_stack --> _rewrite_yaml
    _render_value --> _render_value
    _render_value --> _fmt_scalar
    _render_value --> _fmt_scalar
    render_config_yaml --> _render_stack_line
    render_config_yaml --> _render_value
    render_config_yaml --> _fmt_scalar
    _rewrite_yaml --> render_config_yaml
    generate_default_yaml --> _render_stack_line
    schema_config_report --> find_pactkit_yaml
    schema_config_report --> load_config
    schema_config_report --> get_default_config
    _is_duplicate --> _jaccard_similarity
    _repair_table_structure --> ContinuationEngine_start
    append_lesson --> _get_last_n_entries
    append_lesson --> _is_duplicate
    append_lesson --> _rotate_if_needed
    append_lesson --> _repair_table_structure
    append_lesson --> _is_specific
    check_init_markers --> find_pactkit_yaml
    check_config_completeness --> find_pactkit_yaml
    check_version_mismatch --> _get_global_version_marker
    check_version_mismatch --> _parse_version
    check_version_mismatch --> _parse_version
    rollback_paths --> _minimal_paths
    rollback_paths --> _remove_path
    _has_dir_with_files --> _all_config_dirs
    _check_h1 --> _has_dir_with_files
    _check_h1 --> _has_dir_with_files
    _check_h1 --> _compute_layer_level
    _check_h1 --> _all_config_dirs
    _check_h2 --> _compute_layer_level
    _check_h2 --> _all_config_dirs
    _check_h2 --> _all_config_dirs
    _check_h3 --> _all_config_dirs
    _check_h3 --> _compute_layer_level
    _check_h4 --> _all_config_dirs
    _check_h4 --> _compute_layer_level
    _check_h4 --> _all_config_dirs
    _check_h5 --> _all_config_dirs
    _check_h5 --> _all_config_dirs
    _check_h5 --> _compute_layer_level
    _check_h6 --> _all_config_dirs
    _check_h6 --> _all_config_dirs
    _check_h6 --> _compute_layer_level
    _check_h7 --> _compute_layer_level
    _collect_findings --> check_dead_imports
    _collect_insights --> LessonRepository_add
    _collect_insights --> LessonRepository_add
    _collect_insights --> LessonRepository_add
    _collect_insights --> LessonRepository_add
    _collect_insights --> LessonRepository_add
    _collect_insights --> _collect_insights__dfs
    _collect_insights --> _collect_insights__dfs
    _check_code_smells --> _max_nesting_depth
    _max_nesting_depth --> _max_nesting_depth
    _max_nesting_depth --> _max_nesting_depth
    _check_dependency_health --> _flatten_pip_audit_vulns
    _compute_hotspots --> _check_test_coverage
    _compute_hotspots --> _check_docstring_coverage
    _compute_hotspots --> _check_code_smells
    _compute_hotspots --> _suggest_action
    _generate_suggested_tasks --> _find_existing_spec
    _generate_suggested_tasks --> generate_item_id
    _generate_suggested_tasks --> _scaffold_audit_spec
    audit --> _compute_score
    audit --> _compute_hotspots
    audit --> _check_dependency_health
    audit --> _collect_findings
    audit --> _collect_insights
    audit --> _write_audit_json
    audit --> _should_refresh_audit
    audit --> _run_layer
    audit --> _run_layer
    audit --> _generate_suggested_tasks
    audit --> find_pactkit_yaml
    audit --> _check_h1
    audit --> _check_h2
    audit --> _check_h3
    audit --> _check_h4
    audit --> _check_h5
    audit --> _check_h6
    audit --> _check_h7
    audit --> load_config
    _collect_insights__dfs --> LessonRepository_add
    _collect_insights__dfs --> LessonRepository_add
    _collect_insights__dfs --> _collect_insights__dfs
    _check_completion --> _pass
    _check_completion --> _tests_pass
    _done_completion --> _pass
    _sprint_completion --> _nonempty
    _hotfix_completion --> _tests_pass
    _release_completion --> _nonempty
    _release_completion --> _nonempty
    _release_completion --> _nonempty
    _pr_completion --> _nonempty
    _pr_completion --> _nonempty
    _pr_completion --> _nonempty
    _debug_completion --> _nonempty
    _debug_completion --> _nonempty
    _debug_completion --> _nonempty
    NoopValidator_validate --> PlanEvidenceValidator_validate
    NoopValidator_validate --> ProjectCommandValidator_validate
    NoopValidator_validate --> ActEvidenceValidator_validate
    NoopValidator_fingerprints --> PlanEvidenceValidator_fingerprints
    NoopValidator_revalidate_artifacts --> PlanEvidenceValidator_revalidate_artifacts
    NoopValidator__require_graph_evidence --> find_pactkit_yaml
    NoopValidator__require_graph_evidence --> load_config
    PlanEvidenceValidator_validate --> ActEvidenceValidator_validate
    PlanEvidenceValidator_validate --> PlanEvidenceValidator__spec
    PlanEvidenceValidator_validate --> PlanEvidenceValidator__require_requirements
    PlanEvidenceValidator_validate --> PlanEvidenceValidator__require_acceptance
    PlanEvidenceValidator_validate --> PlanEvidenceValidator__require_security
    PlanEvidenceValidator_validate --> PlanEvidenceValidator__spec
    PlanEvidenceValidator_validate --> PlanEvidenceValidator__require_lint
    PlanEvidenceValidator_validate --> PlanEvidenceValidator__require_board
    PlanEvidenceValidator_validate --> PlanEvidenceValidator__require_complete
    PlanEvidenceValidator__text --> PlanEvidenceValidator__spec
    PlanEvidenceValidator__require_requirements --> PlanEvidenceValidator__text
    PlanEvidenceValidator__require_acceptance --> PlanEvidenceValidator__text
    PlanEvidenceValidator__require_security --> PlanEvidenceValidator__text
    PlanEvidenceValidator__require_lint --> PlanEvidenceValidator__spec
    PlanEvidenceValidator__require_board --> StoryRepository_load
    PlanEvidenceValidator__require_board --> PlanEvidenceValidator__board
    PlanEvidenceValidator__require_board --> PlanEvidenceValidator__board
    PlanEvidenceValidator__require_board --> ContinuationEngine_start
    PlanEvidenceValidator__require_complete --> PlanEvidenceValidator__require_requirements
    PlanEvidenceValidator__require_complete --> PlanEvidenceValidator__require_acceptance
    PlanEvidenceValidator__require_complete --> PlanEvidenceValidator__require_security
    PlanEvidenceValidator__require_complete --> PlanEvidenceValidator__require_lint
    PlanEvidenceValidator_fingerprints --> _hash
    PlanEvidenceValidator_fingerprints --> _hash
    PlanEvidenceValidator_fingerprints --> _hash
    PlanEvidenceValidator_fingerprints --> _hash
    PlanEvidenceValidator_fingerprints --> PlanEvidenceValidator__spec
    PlanEvidenceValidator_fingerprints --> PlanEvidenceValidator__board
    PlanEvidenceValidator_revalidate_artifacts --> PlanEvidenceValidator_validate
    ProjectCommandValidator_validate --> ActEvidenceValidator_validate
    ActEvidenceValidator_validate --> ActEvidenceValidator_validate
    detect_security_scope --> _is_docs_or_tests_only
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> _read_content
    detect_security_scope --> _path_ends_with_ext
    detect_security_scope --> _path_matches_any
    detect_security_scope --> _path_ends_with_ext
    detect_security_scope --> _path_matches_any
    detect_security_scope --> _path_matches_any
    detect_security_scope --> _path_matches_any
    detect_security_scope --> _path_ends_with_ext
    check_dead_imports --> _resolve_scope
    check_dead_imports --> _python_files
    check_dead_imports --> ContinuationEngine_start
    check_dead_imports --> ContinuationEngine_start
    check_dead_imports --> ContinuationEngine_start
    check_dead_imports --> ContinuationEngine_start
    check_dead_imports --> ContinuationEngine_start
    check_stale_docs --> context_output_path
    check_stale_docs --> ContinuationStore_diagnostics
    check_stale_docs --> LessonRepository_add
    check_pattern_duplication --> _resolve_scope
    check_pattern_duplication --> _python_files
    check_pattern_duplication --> ContinuationEngine_start
    run_garden --> check_dead_imports
    run_garden --> check_stale_docs
    run_garden --> check_pattern_duplication
    __module__ --> _generate_project_claude_md
    record_status --> atomic_write
    record_status --> _status_path
    record_attempt --> atomic_write
    record_attempt --> _status_path
    read_status --> _status_path
    _no_git_enabled --> load_config
    _no_git_enabled --> load_config
    _pytest_interpreter --> pytest_command
    probe_commit_gate --> _no_git_enabled
    probe_commit_gate --> stack_test_command
    probe_commit_gate --> _pytest_interpreter
    probe_coverage_gate --> _pytest_interpreter
    probe_coverage_gate --> _module_available
    probe_push_gate --> _no_git_enabled
    probe_tamper_guard --> _no_git_enabled
    probe_tamper_guard --> _enforcement_settings
    _probe_flag_gate --> _no_git_enabled
    _probe_flag_gate --> _enforcement_settings
    _merge --> ContinuationStore_status
    _merge --> ContinuationStore_status
    assess --> _merge
    assess --> read_status
    _probe_flag_gate__probe --> _no_git_enabled
    _probe_flag_gate__probe --> _enforcement_settings
    collect_changed_files --> _git
    collect_changed_files --> _git
    current_branch --> _git
    _pytest_command --> pytest_command
    run_pytest --> stack_test_command
    run_pytest --> _pytest_command
    run_pytest --> parse_junit_counts
    decide_test_set --> current_branch
    decide_test_set --> _enforcement_settings
    decide_test_set --> classify_changes
    decide_test_set --> map_to_tests
    _refspec_target --> current_branch
    resolve_push_target --> _refspec_target
    resolve_push_target --> current_branch
    resolve_push_target --> current_branch
    resolve_push_target --> _refspec_target
    check_push --> _enforcement_settings
    check_push --> resolve_push_target
    check_push --> record_status
    check_push --> record_gate_event
    check_push --> record_attempt
    check_push --> record_status
    check_push --> record_status
    check_push --> record_status
    check_push --> record_status
    run_gate --> record_attempt
    run_gate --> collect_changed_files
    run_gate --> decide_test_set
    run_gate --> run_pytest
    run_gate --> parse_pytest_summary
    run_gate --> record_status
    run_gate --> record_status
    run_gate --> record_status
    run_gate --> record_status
    run_gate --> record_gate_event
    run_gate --> record_gate_event
    run_gate --> record_status
    run_gate --> record_status
    run_gate --> record_status
    hook_entry --> _command_root
    hook_entry --> run_gate
    hook_entry --> check_edit_tool
    hook_entry --> record_gate_event
    hook_entry --> check_push
    hook_entry --> check_bash_command
    hook_entry --> render
    _enforcement_settings --> load_config
    install_hook --> _no_git_enabled
    install_hook --> _merge_pre_tooluse_entry
    install_hook --> _merge_event_entry
    install_codex_hook --> _no_git_enabled
    install_codex_hook --> _hooks_json_lock
    install_codex_hook --> _merge_pre_tooluse_entry
    install_git_hook --> _no_git_enabled
    install_pre_push_hook --> _no_git_enabled
    gate_channel --> _no_git_enabled
    gate_channel --> _codex_hook_present
    ensure_gate_channel --> gate_channel
    ensure_gate_channel --> install_hook
    ensure_gate_channel --> install_codex_hook
    ensure_gate_channel --> install_pre_push_hook
    ensure_gate_channel --> install_codex_hook
    ensure_gate_channel --> install_git_hook
    ensure_gate_channel --> install_pre_push_hook
    ensure_gate_channel --> install_git_hook
    ensure_gate_channel --> install_pre_push_hook
    check_command --> scan_command
    check_command --> record_status
    check_command --> record_gate_event
    check_command --> _enforcement_settings
    check_command --> redact_command
    check_command --> match_scope
    check_command --> _token_valid
    check_command --> record_status
    check_command --> record_gate_event
    check_command --> record_gate_event
    check_command --> _enforcement_settings
    check_command --> record_status
    check_command --> record_status
    check_command --> redact_command
    check_command --> redact_command
    _summarize --> _parse_ts
    _summarize --> _parse_ts
    collect_runs --> LessonRepository_add
    collect_runs --> LessonRepository_add
    collect_runs --> read_events
    collect_runs --> LessonRepository_add
    collect_runs --> read_events
    collect_runs --> LessonRepository_add
    collect_runs --> _unavailable
    collect_runs --> _unavailable
    collect_runs --> _summarize
    collect_runs --> _summarize
    collect_runs --> ContinuationStore_status
    collect_runs --> ContinuationStore_status
    collect_runs --> ContinuationStore_status
    collect_runs --> ContinuationStore_status
    collect_gate_telemetry --> gate_events_path
    collect_gate_telemetry --> read_events
    run_lint --> detect_stack
    run_lint --> find_pactkit_yaml
    run_lint --> _add_fix_flag
    run_lint --> load_config
    build_change_risk_profile --> _is_docs_only
    resolve_project_root --> _is_initialized
    resolve_project_root --> _is_initialized
    expected_components --> is_environment_format
    expected_components --> get_profile
    load_previous_hashes --> load_previous_manifest
    preserve_or_write --> atomic_write
    preserve_or_write --> atomic_write
    preserve_or_write --> atomic_write
    retire_disabled_skills --> load_previous_manifest
    pactkit_owned_files --> sha256_file
    pactkit_owned_files --> sha256_file
    pactkit_owned_files --> sha256_file
    pactkit_owned_files --> sha256_file
    pactkit_owned_files --> sha256_file
    pactkit_owned_files --> normalize_rule_id
    pactkit_rule_ownership --> normalize_rule_id
    pactkit_rule_ownership --> sha256_file
    pactkit_rule_ownership --> sha256_file
    write_deploy_manifest --> expected_components
    write_deploy_manifest --> expected_components
    write_deploy_manifest --> pactkit_rule_ownership
    write_deploy_manifest --> pactkit_owned_files
    should_visualize --> detect_stack
    run_visualize_single --> _print_codegraph_sync
    run_visualize_graphs --> _print_codegraph_sync
    _print_codegraph_sync --> codegraph_sync
    verification_outcome_unknown --> pid_alive
    verification_outcome_unknown --> read_status
    _sanitize_evidence --> _sanitize
    _sanitize_evidence --> _sanitize_evidence
    _sanitize_evidence --> _sanitize_evidence
    ContinuationEngine__run_lock --> ContinuationEngine_path_for
    ContinuationEngine_definition --> get_workflow
    ContinuationEngine_path_for --> ContinuationEngine__validate_run_id
    ContinuationEngine__find --> ContinuationEngine_path_for
    ContinuationEngine_read --> ContinuationEngine__find
    ContinuationEngine_bind_host_session --> ContinuationEngine__find
    ContinuationEngine_bind_host_session --> ContinuationEngine__host_reference
    ContinuationEngine_bind_host_session --> ContinuationEngine__host_reference
    ContinuationEngine_bind_host_session --> ContinuationEngine__run_lock
    ContinuationEngine_bind_host_session --> ContinuationEngine__find
    ContinuationEngine_bind_host_session --> atomic_write
    ContinuationEngine_bind_host_session --> atomic_write
    ContinuationEngine_bind_host_session --> ContinuationEngine__host_binding_path
    ContinuationEngine_resolve_host_run --> ContinuationEngine__host_reference
    ContinuationEngine_resolve_host_run --> ContinuationEngine__host_binding_path
    ContinuationEngine_resolve_host_run --> ContinuationEngine__host_resolution
    ContinuationEngine_resolve_host_run --> ContinuationEngine__host_reference
    ContinuationEngine_resolve_host_run --> ContinuationEngine__host_resolution
    ContinuationEngine_resolve_host_run --> ContinuationEngine_read
    ContinuationEngine_start --> ContinuationEngine_definition
    ContinuationEngine_start --> _sanitize_evidence
    ContinuationEngine_start --> ActEvidenceValidator_validate
    ContinuationEngine_start --> ContinuationEngine__run_lock
    ContinuationEngine_start --> atomic_write
    ContinuationEngine_start --> append_event
    ContinuationEngine_start --> ContinuationEngine_path_for
    ContinuationEngine_start --> run_events_path
    ContinuationEngine_start --> _sanitize_evidence
    ContinuationEngine_bind_story --> ContinuationEngine__find
    ContinuationEngine_bind_story --> ContinuationEngine__bind_lock
    ContinuationEngine_bind_story --> ContinuationEngine__run_lock
    ContinuationEngine_bind_story --> ContinuationEngine__find
    ContinuationEngine_bind_story --> atomic_write
    ContinuationEngine_checkpoint --> ContinuationEngine__find
    ContinuationEngine_checkpoint --> ContinuationEngine__run_lock
    ContinuationEngine_checkpoint --> ContinuationEngine__find
    ContinuationEngine_checkpoint --> ContinuationEngine_definition
    ContinuationEngine_checkpoint --> atomic_write
    ContinuationEngine_checkpoint --> ContinuationEngine__emit_run_events
    ContinuationEngine_checkpoint --> ActEvidenceValidator_validate
    ContinuationEngine_checkpoint --> ContinuationStore_status
    ContinuationEngine_checkpoint --> _sanitize_evidence
    ContinuationEngine_checkpoint --> _sanitize
    ContinuationEngine_checkpoint --> NoopValidator_fingerprints
    ContinuationEngine__emit_run_events --> run_events_path
    ContinuationEngine__emit_run_events --> append_event
    ContinuationEngine__emit_run_events --> append_event
    ContinuationEngine__emit_run_events --> append_event
    ContinuationEngine__emit_run_events --> append_event
    ContinuationEngine__emit_run_events --> append_event
    ContinuationEngine__emit_run_events --> append_event
    ContinuationEngine__emit_run_events --> append_event
    ContinuationEngine__emit_run_events --> _sanitize_evidence
    ContinuationEngine__emit_run_events --> _sanitize
    ContinuationEngine_resume --> ContinuationEngine__find
    ContinuationEngine_resume --> NoopValidator_fingerprints
    ContinuationEngine_resume --> ContinuationEngine_definition
    ContinuationEngine_resume --> ContinuationEngine_definition
    ContinuationEngine_revalidate_artifacts --> ContinuationEngine__find
    ContinuationEngine_revalidate_artifacts --> ContinuationEngine_resume
    ContinuationEngine_revalidate_artifacts --> ContinuationEngine__run_lock
    ContinuationEngine_revalidate_artifacts --> ContinuationEngine__find
    ContinuationEngine_revalidate_artifacts --> NoopValidator_fingerprints
    ContinuationEngine_revalidate_artifacts --> audit
    ContinuationEngine_revalidate_artifacts --> atomic_write
    ContinuationEngine_revalidate_artifacts --> append_event
    ContinuationEngine_revalidate_artifacts --> ContinuationEngine_revalidate_artifacts
    ContinuationEngine_revalidate_artifacts --> run_events_path
    ContinuationEngine_revalidate_artifacts --> ContinuationEngine_definition
    ContinuationEngine_revalidate_artifacts --> _sanitize_evidence
    ContinuationEngine_finish_guard --> ContinuationStore__generic_act_resolution
    ContinuationEngine_finish_guard --> ContinuationEngine_read
    ContinuationEngine_finish_guard --> ContinuationEngine__find
    ContinuationEngine_finish_guard --> ContinuationEngine_definition
    ContinuationEngine_finish_guard --> NoopValidator_fingerprints
    ContinuationEngine_finish_guard --> verification_outcome_unknown
    ContinuationEngine_finish_guard --> ContinuationStore__ambiguous_generic_act_result
    ContinuationEngine_finish_guard --> ContinuationEngine__legacy_finish_guard
    ContinuationEngine_finish_guard --> HostCapabilities_auto_resume_available
    ContinuationEngine_finish_guard --> ContinuationEngine__find
    ContinuationEngine_finish_guard --> HostCapabilities_auto_resume_available
    ContinuationEngine_finish_guard --> ActEvidenceValidator_validate
    ContinuationEngine_finish_guard --> _sanitize
    ContinuationEngine_finish_guard --> _sanitize
    ContinuationEngine__legacy_finish_guard --> ContinuationEngine_resume
    ContinuationEngine_validate_managed_operation --> ContinuationEngine__find
    ContinuationEngine_validate_managed_operation --> ContinuationEngine_definition
    ContinuationStore_path_for --> ContinuationStore__validate_story_id
    ContinuationStore__generic_act_resolution --> ContinuationEngine_finish_guard
    ContinuationStore__generic_act_resolution --> ContinuationEngine_read
    ContinuationStore__fingerprints --> ContinuationStore__paths
    ContinuationStore__fingerprints --> ContinuationStore__story_fact_path
    ContinuationStore__fingerprints --> _fingerprint
    ContinuationStore__fingerprints --> _git_head
    ContinuationStore__fingerprints --> _worktree_fingerprint
    ContinuationStore__fingerprints --> _fingerprint
    ContinuationStore__fingerprints --> _fingerprint
    ContinuationStore_read --> ContinuationStore__validate_story_id
    ContinuationStore_read --> ContinuationStore_path_for
    ContinuationStore_legacy_handoff --> ContinuationStore__validate_story_id
    ContinuationStore_deny --> ContinuationStore__validate_story_id
    ContinuationStore_deny --> _sanitize
    ContinuationStore_deny --> ContinuationStore__story_lock
    ContinuationStore_deny --> ContinuationStore_read
    ContinuationStore_deny --> atomic_write
    ContinuationStore_deny --> append_event
    ContinuationStore_deny --> _sanitize
    ContinuationStore_deny --> ContinuationStore_path_for
    ContinuationStore_deny --> story_events_path
    ContinuationStore_deny --> _sanitize_evidence
    ContinuationStore_status --> ContinuationStore__validate_story_id
    ContinuationStore_status --> ContinuationStore__generic_act_resolution
    ContinuationStore_status --> ContinuationStore_read
    ContinuationStore_status --> ContinuationStore_legacy_handoff
    ContinuationStore_status --> ContinuationStore__ambiguous_generic_act_result
    ContinuationStore__story_lock --> ContinuationStore_path_for
    ContinuationStore_checkpoint --> ContinuationStore__story_lock
    ContinuationStore_checkpoint --> ContinuationStore__checkpoint_locked
    ContinuationStore_checkpoint --> ContinuationStore_status
    ContinuationStore__checkpoint_locked --> ContinuationStore__validate_story_id
    ContinuationStore__checkpoint_locked --> ContinuationStore__validate_step_evidence
    ContinuationStore__checkpoint_locked --> ContinuationStore_read
    ContinuationStore__checkpoint_locked --> atomic_write
    ContinuationStore__checkpoint_locked --> ContinuationStore__emit_checkpoint_events
    ContinuationStore__checkpoint_locked --> ContinuationStore__stale_reasons
    ContinuationStore__checkpoint_locked --> ContinuationStore__archive_completed
    ContinuationStore__checkpoint_locked --> ContinuationStore__validate_completion
    ContinuationStore__checkpoint_locked --> _sanitize
    ContinuationStore__checkpoint_locked --> _sanitize_evidence
    ContinuationStore__checkpoint_locked --> _sanitize
    ContinuationStore__checkpoint_locked --> ContinuationStore_path_for
    ContinuationStore__checkpoint_locked --> ContinuationStore__fingerprints
    ContinuationStore__checkpoint_locked --> ContinuationStore__stale_reasons
    ContinuationStore__emit_checkpoint_events --> story_events_path
    ContinuationStore__emit_checkpoint_events --> append_event
    ContinuationStore__emit_checkpoint_events --> append_event
    ContinuationStore__emit_checkpoint_events --> append_event
    ContinuationStore__emit_checkpoint_events --> append_event
    ContinuationStore__emit_checkpoint_events --> append_event
    ContinuationStore__emit_checkpoint_events --> append_event
    ContinuationStore__emit_checkpoint_events --> append_event
    ContinuationStore__emit_checkpoint_events --> _sanitize_evidence
    ContinuationStore__emit_checkpoint_events --> _sanitize_evidence
    ContinuationStore__emit_checkpoint_events --> _sanitize_evidence
    ContinuationStore__emit_checkpoint_events --> _sanitize_evidence
    ContinuationStore__validate_step_evidence --> ContinuationStore__require_valid_spec
    ContinuationStore__validate_step_evidence --> ActEvidenceValidator_validate
    ContinuationStore__validate_step_evidence --> get_workflow
    ContinuationStore__require_valid_spec --> ContinuationStore__paths
    ContinuationStore__archive_completed --> atomic_write
    ContinuationStore__archive_completed --> append_event
    ContinuationStore__archive_completed --> story_events_path
    ContinuationStore__archive_completed --> _sanitize_evidence
    ContinuationStore__validate_completion --> ContinuationStore__require_valid_spec
    ContinuationStore__validate_completion --> ContinuationStore__story_fact_path
    ContinuationStore__validate_completion --> ContinuationStore__paths
    ContinuationStore__validate_completion --> StoryRepository_load
    ContinuationStore__validate_completion --> ContinuationStore__paths
    ContinuationStore_resume --> ContinuationStore__validate_story_id
    ContinuationStore_resume --> ContinuationStore__generic_act_resolution
    ContinuationStore_resume --> ContinuationStore_read
    ContinuationStore_resume --> ContinuationStore__active_peer_story_ids
    ContinuationStore_resume --> verification_outcome_unknown
    ContinuationStore_resume --> ContinuationStore__ambiguous_generic_act_result
    ContinuationStore_resume --> ContinuationStore_status
    ContinuationStore_resume --> validate_skill_recovery_contracts
    ContinuationStore_resume --> ContinuationStore__stale_reasons
    ContinuationStore__stale_reasons --> ContinuationStore__fingerprints
    ContinuationStore__active_peer_story_ids --> ContinuationStore_read
    ContinuationStore_diagnostics --> ContinuationStore_read
    ContinuationStore_diagnostics --> ContinuationStore_path_for
    ContinuationStore_diagnostics --> ContinuationStore_resume
    _checkpoint_continuation --> _extract_sprint_contract
    _checkpoint_continuation --> ContinuationEngine_read
    _checkpoint_continuation --> ContinuationEngine_resume
    _generate_continuation --> _sanitize_text
    _generate_continuation --> _sanitize_text
    _generate_continuation --> _parse_active_stories
    _generate_continuation --> _checkpoint_continuation
    _generate_continuation --> _extract_sprint_contract
    _generate_continuation --> _checkpoint_continuation
    _generate_continuation --> _sanitize_text
    generate_context --> _get_git_branches
    generate_context --> LessonRepository_recent
    generate_context --> _generate_continuation
    generate_context --> render
    generate_context --> _parse_board
    generate_context --> _parse_active_stories
    generate_context --> _parse_recent_completions
    generate_context --> _parse_last_lessons
    _record --> _record_gate
    _record --> record_status
    _record_gate --> record_gate_event
    _record_gate --> record_status
    _spec_edit_allowed --> _token_valid
    _check_spec_path --> _spec_edit_allowed
    _check_spec_path --> _record_gate
    _check_spec_path --> _receipt_exists
    check_edit_tool --> _relpath
    check_edit_tool --> _check_spec_path
    check_edit_tool --> _is_fully_protected
    check_edit_tool --> _enforcement_settings
    check_edit_tool --> _bypassed
    check_edit_tool --> _record
    check_edit_tool --> _removes_gate_entry
    check_edit_tool --> _record
    check_bash_command --> _record
    check_bash_command --> _enforcement_settings
    check_bash_command --> _bypassed
    check_bash_command --> _receipt_exists
    check_bash_command --> _record
    check_bash_command --> _spec_edit_allowed
    check_bash_command --> _record_gate
    run_observe --> _detect_sources
    run_observe --> _collect_signals
    run_observe --> classify_signals
    run_observe --> build_report
    _schema_command --> schema_config_report
    _run_deploy_command --> deploy
    _run_deploy_command --> _check_adapter_compat
    _run_deploy_command --> sync_config_copies
    _run_deploy_command --> render_check_report
    _run_deploy_command --> check_deps
    _run_deploy_command --> ensure_gate_channel
    main --> main__add_deploy_args
    main --> main__add_deploy_args
    main --> main__add_deploy_args
    main --> _run_deploy_command
    main --> resolve_project_root
    main --> run_spec_preflight
    main --> _schema_command
    main --> check_init_markers
    main --> check_version_mismatch
    main --> load_config
    main --> generate_item_id
    main --> clean_artifacts
    main --> scrub_enforcement_records
    main --> classify_changes
    main --> generate_context
    main --> context_output_path
    main --> atomic_write
    main --> LessonRepository_add
    main --> GovernanceMigrator_migrate
    main --> record_legacy_usage
    main --> StoryRepository_complete_task
    main --> record_legacy_usage
    main --> StoryRepository_move
    main --> ContinuationEngine_checkpoint
    main --> record_legacy_usage
    main --> atomic_write
    main --> ContinuationStore_status
    main --> validate_registry
    main --> render
    main --> _validate_story_id
    main --> read_events
    main --> get_workflow
    main --> detect_security_scope
    main --> BoardRenderer_check
    main --> story_events_path
    main --> ContinuationStore_deny
    main --> ContinuationEngine_resume
    main --> ContinuationEngine_start
    main --> ContinuationEngine_start
    main --> format_markdown_table
    main --> lint_context
    main --> ContinuationEngine_bind_host_session
    main --> ContinuationEngine_read
    main --> ContinuationEngine_bind_story
    main --> WorkflowEngine_acquire
    main --> lint_lessons
    main --> main__workflow_evidence
    main --> ContinuationEngine_checkpoint
    main --> WorkflowEngine_renew
    main --> lint_testcase
    main --> ContinuationEngine_read
    main --> WorkflowEngine_reject
    main --> main__workflow_evidence
    main --> ContinuationEngine_finish_guard
    main --> WorkflowEngine_retry
    main --> WorkflowEngine_expire
    main --> should_visualize
    main --> run_visualize_single
    main --> run_visualize_graphs
    main --> codegraph_sync
    main --> ContinuationEngine_revalidate_artifacts
    main --> ContinuationEngine_resume
    main --> run_garden
    main --> WorkflowEngine_submit
    main --> WorkflowEngine_record_turn_terminal
    main --> codegraph_sync
    main --> run_observe
    main --> PlanFinalizer_finalize
    main --> collect_runs
    main --> collect_gate_telemetry
    main --> PlanFinalizer_finalize
    main --> main__unit_json
    main --> ContinuationEngine_resume
    main --> render_report
    main --> ContinuationStore_status
    main --> json_report
    main --> check_legacy_engine_usage
    main --> check_orphaned_specs
    main --> check_config_drift
    main --> check_graph_provider
    main --> check_stale_graphs
    main --> check_hld_module_count
    main --> check_config_copy_drift
    main --> check_deps
    main --> check_deploy_parity
    main --> check_rule_ownership
    main --> resolve_rule_context
    main --> check_codex_execution_capability
    main --> check_codex_hook_capability
    main --> check_adapter_skew
    main --> check_core_metadata_divergence
    main --> ContinuationStore_diagnostics
    main --> check_workflow_continuation
    main --> main__unit_json
    main --> ContinuationEngine_bind_story
    main --> render_summary
    main --> scan_and_replace_tbd
    main --> check_legacy_engine_usage
    main --> check_orphaned_specs
    main --> check_config_drift
    main --> check_graph_provider
    main --> check_deploy_parity
    main --> check_codex_execution_capability
    main --> check_codex_hook_capability
    main --> check_workflow_continuation
    main --> issue_sync
    main --> map_to_tests
    main --> run_lint
    main --> _is_specific
    main --> _is_duplicate
    main --> refresh_test_count
    main --> LessonRepository_add
    main --> check_coverage
    main --> update_spec_status
    main --> LessonRepository_recent
    main --> verify_story
    main --> check_deps
    main --> render
    main --> install_deps
    main --> render_check_report
    main --> run_gate
    main --> session_start_entry
    main --> pre_compact_entry
    main --> authorize
    main --> check_push
    main --> hook_entry
    main --> render
    main --> install_git_hook
    main --> ContinuationEngine_read
    main --> detect_stacks
    main --> update_yaml_stack
    main --> load_config
    main --> BuiltinGraphProvider_query
    main --> project_router
    main --> GraphQueryResult_to_dict
    main --> load_story_graph
    main --> compute_waves
    main --> render
    main --> render_mermaid
    main --> to_json
    _check_adapter_compat --> check_adapter_compat
    _get_done_ids --> ContinuationEngine_start
    scan_and_replace_tbd --> _get_done_ids
    pytest_command --> detect_venv
    stack_test_command --> detect_stacks
    stack_test_command --> pytest_command
    stack_test_command --> pytest_command
    detect_stacks --> LessonRepository_add
    detect_stacks --> LessonRepository_add
    detect_stack --> detect_stacks
    clean_artifacts --> detect_stack
    clean_artifacts --> _inside_protected
    clean_artifacts --> _inside_protected
    scrub_enforcement_records --> redact_command
    record_gate_event --> append_event
    record_gate_event --> gate_events_path
    record_gate_event --> active_story_id
    parse_story --> _parse_field_table
    parse_story --> _parse_touches
    parse_story --> ContinuationStore_status
    parse_story --> _parse_field_table
    load_story_graph --> parse_story
    compute_conflicts --> _paths_overlap
    render --> compute_waves
    render --> compute_conflicts
    to_json --> compute_waves
    to_json --> compute_conflicts
    _parse_coverage_output --> _classify_coverage
    _run_pytest_cov --> _pytest_command
    check_coverage --> _parse_coverage_output
    check_coverage --> _record
    check_coverage --> _record
    check_coverage --> _extract_module_path
    check_coverage --> _run_pytest_cov
    check_coverage --> _record
    check_coverage --> _record
    authorize --> authorization_path
    authorize --> record_gate_event
    _token_valid --> authorization_path
    _get_issue_tracker_provider --> find_pactkit_yaml
    issue_sync --> _parse_item_type
    issue_sync --> _get_issue_tracker_provider
    issue_sync --> _search_issue
    issue_sync --> _create_issue
    issue_sync --> _check_gh_available
    map_to_tests --> detect_stack
    _board_block --> WorkflowEngine__start
    _story_fact_block --> StoryRepository_load
    _archived --> _read
    check_requirement_evidence --> _read
    check_requirement_evidence --> _read
    check_requirement_evidence --> _parse_ac_to_reqs
    check_requirement_evidence --> _parse_requirements
    check_requirement_evidence --> check_requirement_evidence__mentioned
    check_requirement_evidence --> check_requirement_evidence__mentioned
    check_requirement_evidence --> check_requirement_evidence__mentioned
    check_requirement_evidence --> map_to_tests
    check_archive_honesty --> _strip_code_spans
    check_archive_honesty --> _read
    _changed_source_files --> _git
    _changed_source_files --> _git
    _changed_source_files --> LessonRepository_add
    _new_public_symbols --> _git
    _new_public_symbols --> _read
    _new_public_symbols --> _git
    check_wiring --> _changed_source_files
    check_wiring --> _new_public_symbols
    check_wiring --> _has_production_caller
    check_status_consistency --> _read
    check_status_consistency --> _spec_status
    check_status_consistency --> _archived
    verify_story --> _story_fact_block
    verify_story --> _read
    verify_story --> _board_block
    verify_story --> check_requirement_evidence
    verify_story --> check_archive_honesty
    verify_story --> check_wiring
    verify_story --> check_status_consistency
    verify_story --> BoardRenderer_check
    resolve_rule_context --> ContinuationEngine_definition
    _project_deploy_dirs --> is_environment_format
    _project_host_guarantees --> _project_deploy_dirs
    check_legacy_engine_usage --> read_legacy_usage
    check_workflow_continuation --> _project_host_guarantees
    check_workflow_continuation --> _append_host_warnings
    check_workflow_continuation --> _append_host_warnings
    check_workflow_continuation --> _validate_workflow_state
    check_workflow_continuation --> WorkflowEngine__validate_completed_finalize_journal
    check_orphaned_specs --> LessonRepository_add
    check_config_drift --> find_pactkit_yaml
    check_config_drift --> check_config_drift__exists_in_any
    check_config_drift --> check_config_drift__dir_or_file_in_any
    check_graph_provider --> find_pactkit_yaml
    check_graph_provider --> BuiltinGraphProvider_health
    check_graph_provider --> load_config
    check_stale_graphs --> load_config
    check_stale_graphs --> find_pactkit_yaml
    check_rule_ownership --> LessonRepository_add
    check_rule_ownership --> _project_deploy_dirs
    check_codex_hook_capability --> _codex_cli_version
    check_deploy_parity --> LessonRepository_add
    check_deploy_parity --> expected_components
    check_deploy_parity --> LessonRepository_add
    check_deploy_parity --> LessonRepository_add
    check_deploy_parity --> LessonRepository_add
    check_deploy_parity --> LessonRepository_add
    check_deploy_parity --> sha256_file
    check_adapter_skew --> _major_minor
    check_adapter_skew --> _major_minor
    check_adapter_compat --> _major_minor
    check_adapter_compat --> _major_minor
    GraphProviderError___init__ --> BoardRenderer___init__
    CodegraphProvider_health --> CodegraphProvider__run
    CodegraphProvider_health --> CodegraphProvider__run
    CodegraphProvider_health --> _clean
    CodegraphProvider_health --> _clean
    CodegraphProvider_health --> _clean
    CodegraphProvider_health --> _clean
    CodegraphProvider_sync --> CodegraphProvider__sync_lock
    CodegraphProvider_sync --> CodegraphProvider_health
    CodegraphProvider_sync --> CodegraphProvider__run
    CodegraphProvider_sync --> CodegraphProvider_health
    CodegraphProvider_sync --> _clean
    CodegraphProvider_query --> CodegraphProvider__run
    CodegraphProvider_query --> CodegraphProvider__query_sqlite
    CodegraphProvider_query --> _clean
    CodegraphProvider_query --> _clean
    BuiltinGraphProvider_sync --> BuiltinGraphProvider_health
    TextSearchProvider_sync --> TextSearchProvider_health
    TextSearchProvider_query --> _clean
    TextSearchProvider_query --> _clean
    TextSearchProvider_query --> _clean
    GraphProviderRouter_query --> GraphProviderRouter__query_one
    GraphProviderRouter_query --> GraphProviderRouter__query_one
    GraphProviderRouter__query_one --> BuiltinGraphProvider_health
    GraphProviderRouter__query_one --> BuiltinGraphProvider_query
    GraphProviderRouter__query_one --> BuiltinGraphProvider_sync
    StoryRepository__authorize --> ContinuationEngine_validate_managed_operation
    StoryRepository_path_for --> _validate_item_id
    StoryRepository__validate --> _validate_item_id
    StoryRepository__validate --> LessonRepository_add
    StoryRepository_load --> StoryRepository_path_for
    StoryRepository_load --> StoryRepository__validate
    StoryRepository_list --> StoryRepository_load
    StoryRepository__write --> StoryRepository__validate
    StoryRepository__write --> StoryRepository_path_for
    StoryRepository__write --> atomic_write
    StoryRepository_add --> _validate_item_id
    StoryRepository_add --> StoryRepository__authorize
    StoryRepository_add --> StoryRepository_path_for
    StoryRepository_add --> _now
    StoryRepository_add --> StoryRepository__write
    StoryRepository_add --> StoryRepository_load
    StoryRepository_add --> _task_id
    StoryRepository_add_task --> StoryRepository__authorize
    StoryRepository_add_task --> StoryRepository_load
    StoryRepository_add_task --> _now
    StoryRepository_add_task --> StoryRepository__write
    StoryRepository_add_task --> _task_id
    StoryRepository_complete_task --> StoryRepository__authorize
    StoryRepository_complete_task --> StoryRepository_load
    StoryRepository_complete_task --> _now
    StoryRepository_complete_task --> StoryRepository__write
    StoryRepository_complete_task --> _now
    StoryRepository_move --> ContinuationStore_status
    StoryRepository_move --> StoryRepository__authorize
    StoryRepository_move --> StoryRepository_load
    StoryRepository_move --> _now
    StoryRepository_move --> StoryRepository__write
    StoryRepository_move --> _now
    StoryRepository_move --> _now
    BoardRenderer_render --> ContinuationStore_status
    BoardRenderer_check --> BoardRenderer_render
    LessonRepository_add --> _validate_item_id
    LessonRepository_recent --> LessonRepository__load
    GovernanceMigrator__legacy_stories --> LessonRepository_add
    GovernanceMigrator__legacy_stories --> ContinuationStore_status
    GovernanceMigrator__legacy_stories --> ContinuationEngine_start
    GovernanceMigrator__legacy_stories --> ContinuationEngine_start
    GovernanceMigrator__legacy_stories --> ContinuationEngine_start
    GovernanceMigrator__legacy_lessons --> LessonRepository_add
    GovernanceMigrator_migrate --> GovernanceMigrator__legacy_stories
    GovernanceMigrator_migrate --> GovernanceMigrator__legacy_lessons
    GovernanceMigrator_migrate --> LessonRepository_recent
    GovernanceMigrator_migrate --> LessonRepository_add
    GovernanceMigrator_migrate --> StoryRepository__write
    GovernanceMigrator_migrate --> LessonRepository_import_legacy
    GovernanceMigrator_migrate --> GovernanceMigrator__remove_installed
    _terminal --> _unit
    _dedupe_scope --> LessonRepository_add
    _load_write_scope --> find_pactkit_yaml
    _load_write_scope --> _normalize_write_scope
    _load_write_scope --> load_config
    _load_touches --> parse_story
    resolve_scope --> _load_touches
    resolve_scope --> _normalize_write_scope
    resolve_scope --> _load_write_scope
    resolve_scope --> _dedupe_scope
    resolve_scope --> _dedupe_scope
    _generic_finalize_request_digest --> _validate_fingerprint_map
    _generic_finalize_request_digest --> _is_json_value
    _is_json_value --> _is_json_value
    _is_json_value --> _is_json_value
    _validate_workflow_start --> _validate_story_id
    _receipt_shape_reason --> _is_json_value
    _receipt_shape_reason --> _is_json_value
    _receipt_execution_mode --> select_execution_mode
    _validate_work_unit_record --> _validate_unit_id
    _validate_work_unit_record --> _is_json_value
    _validate_attempt_record --> _is_json_value
    _validate_work_unit_snapshot --> _validate_work_unit_record
    _validate_idempotency_record --> _validate_unit_id
    _validate_idempotency_record --> _validate_identity
    _validate_idempotency_record --> _validate_work_unit_snapshot
    _validate_idempotency_record --> _validate_story_id
    _validate_idempotency_record --> _validate_identity
    _validate_idempotency_record --> _validate_unit_id
    _validate_idempotency_record --> _validate_identity
    _validate_finalize_projection_fingerprints --> _validate_story_id
    _validate_finalize_projection_fingerprints --> StoryRepository_load
    _validate_finalize_projection_fingerprints --> _fingerprint
    _validate_finalize_projection_fingerprints --> context_output_path
    _validate_finalize_projection_fingerprints --> _validate_finalize_projection_fingerprints_normalize_timestamp
    _validate_finalize_projection_fingerprints --> _validate_finalize_projection_fingerprints_normalize_timestamp
    _validate_finalize_projection_fingerprints --> _fingerprint
    _validate_finalize_projection_fingerprints --> render
    _validate_finalize_projection_fingerprints --> generate_context
    _validate_finalize_projection_fingerprints --> _validate_workflow_state
    _validate_finalize_projection_fingerprints --> LessonRepository_add
    _validate_finalize_projection_fingerprints --> LessonRepository_add
    _validate_workflow_state --> _validate_run_id
    _validate_workflow_state --> _validate_fingerprint_map
    _validate_workflow_state --> _validate_story_id
    _validate_workflow_state --> _validate_work_unit_record
    _validate_workflow_state --> _validate_attempt_record
    _validate_workflow_state --> _validate_idempotency_record
    _validate_workflow_state --> _validate_native_workflow_topology
    EvidenceReceipt_for_files --> _fingerprint
    EvidenceReceipt_for_files --> _safe_repo_path
    WorkflowEngine_path_for --> _validate_run_id
    WorkflowEngine__lock --> WorkflowEngine_path_for
    WorkflowEngine__story_lock --> _validate_story_id
    WorkflowEngine__validate_completed_finalize_journal --> _validate_finalize_projection_fingerprints
    WorkflowEngine__validate_completed_finalize_journal --> StoryRepository_load
    WorkflowEngine__validate_completed_finalize_journal --> BoardRenderer_check
    WorkflowEngine__read --> _validate_workflow_state
    WorkflowEngine__read --> WorkflowEngine__validate_completed_finalize_journal
    WorkflowEngine__read --> WorkflowEngine_path_for
    WorkflowEngine__read_scanned_state --> _validate_workflow_state
    WorkflowEngine__read_scanned_state --> WorkflowEngine__validate_completed_finalize_journal
    WorkflowEngine__write --> atomic_write
    WorkflowEngine__write --> WorkflowEngine_path_for
    WorkflowEngine_start --> _validate_workflow_start
    WorkflowEngine_start --> WorkflowEngine__start
    WorkflowEngine_start --> WorkflowEngine__story_lock
    WorkflowEngine_start --> WorkflowEngine__active_runs_for_story
    WorkflowEngine_start --> WorkflowEngine__start
    WorkflowEngine_start --> WorkflowEngine__completed_run_for_story
    WorkflowEngine__start --> WorkflowEngine__run
    WorkflowEngine__start --> WorkflowEngine__lock
    WorkflowEngine__start --> WorkflowEngine__write
    WorkflowEngine__idempotent_unit_result --> _unit
    WorkflowEngine_acquire --> _validate_identity
    WorkflowEngine_acquire --> _timestamp
    WorkflowEngine_acquire --> WorkflowEngine__lock
    WorkflowEngine_acquire --> WorkflowEngine__read
    WorkflowEngine_acquire --> WorkflowEngine__template
    WorkflowEngine_acquire --> resolve_scope
    WorkflowEngine_acquire --> WorkflowEngine__write
    WorkflowEngine_acquire --> WorkflowEngine__unit
    WorkflowEngine_acquire --> WorkflowEngine__idempotent_unit_result
    WorkflowEngine_acquire --> WorkflowEngine__write
    WorkflowEngine_acquire --> _dedupe_scope
    WorkflowEngine_acquire --> _dedupe_scope
    WorkflowEngine_acquire --> render
    WorkflowEngine_acquire --> WorkflowEngine__unit
    WorkflowEngine_acquire --> render
    WorkflowEngine_acquire --> render
    WorkflowEngine_lease_current --> _validate_identity
    WorkflowEngine_lease_current --> WorkflowEngine__read
    WorkflowEngine_lease_current --> WorkflowEngine__template
    WorkflowEngine_lease_current --> WorkflowEngine_retry
    WorkflowEngine_lease_current --> WorkflowEngine_acquire
    WorkflowEngine_lease_current --> WorkflowEngine__read
    WorkflowEngine_lease_current --> WorkflowEngine__template
    WorkflowEngine_lease_current --> WorkflowEngine_retry
    WorkflowEngine__find_run_for_unit --> _validate_unit_id
    WorkflowEngine__find_run_for_unit --> WorkflowEngine__scan_or_skip
    WorkflowEngine__scan_or_skip --> WorkflowEngine__read_scanned_state
    WorkflowEngine__active_runs_for_story --> _validate_story_id
    WorkflowEngine__active_runs_for_story --> WorkflowEngine__scan_or_skip
    WorkflowEngine__completed_run_for_story --> WorkflowEngine__scan_or_skip
    WorkflowEngine_resume --> WorkflowEngine__active_runs_for_story
    WorkflowEngine_resume --> WorkflowEngine__template
    WorkflowEngine_bind_story --> _validate_identity
    WorkflowEngine_bind_story --> _timestamp
    WorkflowEngine_bind_story --> WorkflowEngine__story_lock
    WorkflowEngine_bind_story --> WorkflowEngine__lock
    WorkflowEngine_bind_story --> WorkflowEngine__read
    WorkflowEngine_bind_story --> WorkflowEngine__active_runs_for_story
    WorkflowEngine_bind_story --> WorkflowEngine__run
    WorkflowEngine_bind_story --> WorkflowEngine__write
    WorkflowEngine_bind_story --> WorkflowEngine__idempotent_run_result
    WorkflowEngine_bind_story --> WorkflowEngine__template
    WorkflowEngine_renew --> _validate_identity
    WorkflowEngine_renew --> _timestamp
    WorkflowEngine_renew --> WorkflowEngine__find_run_for_unit
    WorkflowEngine_renew --> WorkflowEngine__lock
    WorkflowEngine_renew --> WorkflowEngine__read
    WorkflowEngine_renew --> WorkflowEngine__write
    WorkflowEngine_renew --> WorkflowEngine__unit
    WorkflowEngine__validate_receipt --> _record_story_id
    WorkflowEngine__validate_receipt --> check_init_markers
    WorkflowEngine__validate_receipt --> _safe_repo_path
    WorkflowEngine__validate_receipt --> _safe_repo_path
    WorkflowEngine__validate_receipt --> _safe_repo_path
    WorkflowEngine__validate_receipt --> _fingerprint
    WorkflowEngine__validate_receipt --> check_init_markers
    WorkflowEngine__validate_receipt --> WorkflowEngine__completed_run_for_story
    WorkflowEngine_reject --> _validate_identity
    WorkflowEngine_reject --> _timestamp
    WorkflowEngine_reject --> WorkflowEngine__find_run_for_unit
    WorkflowEngine_reject --> WorkflowEngine__lock
    WorkflowEngine_reject --> WorkflowEngine__read
    WorkflowEngine_reject --> WorkflowEngine__write
    WorkflowEngine_retry --> _validate_identity
    WorkflowEngine_retry --> _timestamp
    WorkflowEngine_retry --> WorkflowEngine__find_run_for_unit
    WorkflowEngine_retry --> WorkflowEngine__lock
    WorkflowEngine_retry --> WorkflowEngine__read
    WorkflowEngine_retry --> WorkflowEngine__template
    WorkflowEngine_retry --> WorkflowEngine__write
    WorkflowEngine_retry --> WorkflowEngine__unit
    WorkflowEngine_retry --> WorkflowEngine__idempotent_unit_result
    WorkflowEngine_retry --> WorkflowEngine__unit
    WorkflowEngine_expire --> _validate_identity
    WorkflowEngine_expire --> _timestamp
    WorkflowEngine_expire --> WorkflowEngine__find_run_for_unit
    WorkflowEngine_expire --> WorkflowEngine__lock
    WorkflowEngine_expire --> WorkflowEngine__read
    WorkflowEngine_expire --> WorkflowEngine__write
    WorkflowEngine_submit --> _validate_identity
    WorkflowEngine_submit --> _timestamp
    WorkflowEngine_submit --> WorkflowEngine__find_run_for_unit
    WorkflowEngine_submit --> WorkflowEngine__lock
    WorkflowEngine_submit --> WorkflowEngine__read
    WorkflowEngine_submit --> _receipt_shape_reason
    WorkflowEngine_submit --> WorkflowEngine__write
    WorkflowEngine_submit --> _receipt_digest
    WorkflowEngine_submit --> WorkflowEngine__idempotent_submission_result
    WorkflowEngine_submit --> WorkflowEngine__validate_receipt
    WorkflowEngine_submit --> _opaque_ref
    WorkflowEngine_submit --> _opaque_ref
    WorkflowEngine_submit --> _opaque_ref
    WorkflowEngine_submit --> _persisted_fingerprints
    WorkflowEngine_submit --> _receipt_execution_mode
    WorkflowEngine_submit --> WorkflowEngine__template
    WorkflowEngine_record_turn_terminal --> _validate_identity
    WorkflowEngine_record_turn_terminal --> _attempt_metadata
    WorkflowEngine_record_turn_terminal --> select_execution_mode
    WorkflowEngine_record_turn_terminal --> WorkflowEngine__lock
    WorkflowEngine_record_turn_terminal --> WorkflowEngine__read
    WorkflowEngine_record_turn_terminal --> _timestamp
    WorkflowEngine_record_turn_terminal --> WorkflowEngine__write
    WorkflowEngine_record_turn_terminal --> _opaque_ref
    WorkflowEngine_record_turn_terminal --> _opaque_ref
    WorkflowEngine_record_turn_terminal --> _opaque_ref
    WorkflowEngine_record_turn_terminal --> _opaque_ref
    WorkflowEngine_status --> WorkflowEngine__read
    WorkflowEngine_status --> WorkflowEngine__template
    WorkflowEngine_import_legacy --> WorkflowEngine_start
    WorkflowEngine_import_legacy --> WorkflowEngine__run
    WorkflowEngine_import_legacy --> WorkflowEngine__lock
    WorkflowEngine_import_legacy --> WorkflowEngine__read
    WorkflowEngine_import_legacy --> _fingerprint
    WorkflowEngine_import_legacy --> WorkflowEngine__write
    WorkflowEngine__complete_locked --> WorkflowEngine__write
    WorkflowEngine__complete_locked --> WorkflowEngine__template
    WorkflowEngine_plan_ready_to_finalize --> WorkflowEngine__template
    WorkflowEngine_workflow_ready_to_finalize --> WorkflowEngine__template
    PlanFinalizer__story_lock --> _validate_story_id
    PlanFinalizer__write_board --> atomic_write
    PlanFinalizer__write_board --> render
    PlanFinalizer__write_context --> atomic_write
    PlanFinalizer__write_context --> context_output_path
    PlanFinalizer__write_context --> generate_context
    PlanFinalizer__save_journal --> atomic_write
    PlanFinalizer__validate_journal --> _validate_finalize_projection_fingerprints
    PlanFinalizer_finalize --> _validate_identity
    PlanFinalizer_finalize --> _finalize_request_digest
    PlanFinalizer_finalize --> NoopValidator_fingerprints
    PlanFinalizer_finalize --> PlanFinalizer__projection_lock
    PlanFinalizer_finalize --> PlanFinalizer__story_lock
    PlanFinalizer_finalize --> WorkflowEngine__lock
    PlanFinalizer_finalize --> _read
    PlanFinalizer_finalize --> PlanFinalizer__journal_path
    PlanFinalizer_finalize --> PlanFinalizer__save_journal
    PlanFinalizer_finalize --> ContinuationEngine_path_for
    PlanFinalizer_finalize --> StoryRepository_load
    PlanFinalizer_finalize --> PlanFinalizer__save_journal
    PlanFinalizer_finalize --> PlanFinalizer__write_board
    PlanFinalizer_finalize --> PlanFinalizer__save_journal
    PlanFinalizer_finalize --> PlanFinalizer__write_context
    PlanFinalizer_finalize --> PlanFinalizer__save_journal
    PlanFinalizer_finalize --> WorkflowEngine__complete_locked
    PlanFinalizer_finalize --> PlanFinalizer__save_journal
    PlanFinalizer_finalize --> PlanFinalizer__journal_path
    PlanFinalizer_finalize --> PlanFinalizer__validate_journal
    PlanFinalizer_finalize --> _validate_finalize_projection_fingerprints
    PlanFinalizer_finalize --> PlanFinalizer__save_journal
    PlanFinalizer_finalize --> WorkflowEngine_plan_ready_to_finalize
    PlanFinalizer_finalize --> PlanFinalizer__validate_journal
    PlanFinalizer_finalize --> StoryRepository_load
    PlanFinalizer_finalize --> LessonRepository_add
    PlanFinalizer_finalize --> _fingerprint
    PlanFinalizer_finalize --> _fingerprint
    PlanFinalizer_finalize --> _fingerprint
    PlanFinalizer_finalize --> _fingerprint
    PlanFinalizer_finalize --> _fingerprint
    WorkflowFinalizer__save --> atomic_write
    WorkflowFinalizer_finalize --> _validate_identity
    WorkflowFinalizer_finalize --> _receipt_shape_reason
    WorkflowFinalizer_finalize --> _read
    WorkflowFinalizer_finalize --> WorkflowFinalizer__completion_evidence
    WorkflowFinalizer_finalize --> WorkflowFinalizer__validate_completion
    WorkflowFinalizer_finalize --> WorkflowEngine_submit
    WorkflowFinalizer_finalize --> WorkflowEngine__lock
    WorkflowFinalizer_finalize --> _read
    WorkflowFinalizer_finalize --> _generic_finalize_request_digest
    WorkflowFinalizer_finalize --> WorkflowFinalizer__journal_path
    WorkflowFinalizer_finalize --> WorkflowFinalizer__completion_evidence
    WorkflowFinalizer_finalize --> WorkflowFinalizer__validate_completion
    WorkflowFinalizer_finalize --> StoryRepository__write
    WorkflowFinalizer_finalize --> WorkflowFinalizer__save
    WorkflowFinalizer_finalize --> WorkflowEngine_workflow_ready_to_finalize
    WorkflowFinalizer_finalize --> WorkflowEngine_workflow_ready_to_finalize
    WorkflowFinalizer_finalize --> WorkflowFinalizer__save
    WorkflowFinalizer_finalize --> WorkflowFinalizer__complete_act_story_tasks
    WorkflowFinalizer_finalize --> WorkflowFinalizer__save
    WorkflowFinalizer_finalize --> _fingerprint
    WorkflowFinalizer_finalize --> WorkflowFinalizer__complete_act_story_tasks
    WorkflowFinalizer_finalize --> WorkflowFinalizer__save
    WorkflowFinalizer_finalize --> _fingerprint
    WorkflowFinalizer_finalize --> _safe_repo_path
    WorkflowFinalizer_finalize --> WorkflowEngine__template
    WorkflowFinalizer_finalize --> _safe_repo_path
    WorkflowFinalizer__validate_completion --> ActEvidenceValidator_validate
    WorkflowFinalizer__validate_completion --> WorkflowFinalizer__validate_pdca_completion
    WorkflowFinalizer__validate_completion --> project_command_validator
    WorkflowFinalizer__complete_act_story_tasks --> StoryRepository_load
    WorkflowFinalizer__complete_act_story_tasks --> atomic_write
    WorkflowFinalizer__complete_act_story_tasks --> atomic_write
    WorkflowFinalizer__complete_act_story_tasks --> WorkflowFinalizer__validate_act_story_projection
    WorkflowFinalizer__complete_act_story_tasks --> render
    WorkflowFinalizer__complete_act_story_tasks --> context_output_path
    WorkflowFinalizer__complete_act_story_tasks --> generate_context
    WorkflowFinalizer__complete_act_story_tasks --> StoryRepository_complete_task
    WorkflowFinalizer__validate_act_story_projection --> StoryRepository_load
    WorkflowFinalizer__validate_act_story_projection --> BoardRenderer_check
    evaluate_agent_final --> ContinuationEngine_finish_guard
    HostContinuationRunner__session_reference --> _sanitize
    HostContinuationRunner_after_model_turn --> ContinuationEngine_finish_guard
    HostContinuationRunner_after_model_turn --> HostContinuationRunner_record_resume_failure
    HostContinuationRunner_after_model_turn --> HostContinuationRunner__after_legacy_turn
    HostContinuationRunner_after_model_turn --> ContinuationEngine__run_lock
    HostContinuationRunner_after_model_turn --> ContinuationEngine__find
    HostContinuationRunner_after_model_turn --> HostContinuationRunner__digest
    HostContinuationRunner_after_model_turn --> atomic_write
    HostContinuationRunner_after_model_turn --> HostContinuationRunner__session_reference
    HostContinuationRunner_after_model_turn --> ContinuationEngine_finish_guard
    HostContinuationRunner_after_model_turn --> HostContinuationRunner__session_reference
    HostContinuationRunner__after_legacy_turn --> ContinuationEngine_read
    HostContinuationRunner__after_legacy_turn --> HostContinuationRunner__digest
    HostContinuationRunner__after_legacy_turn --> atomic_write
    HostContinuationRunner__after_legacy_turn --> HostContinuationRunner__session_reference
    HostContinuationRunner__after_legacy_turn --> HostContinuationRunner__session_reference
    HostContinuationRunner_before_operation --> ContinuationEngine_finish_guard
    HostContinuationRunner_record_resume_failure --> ContinuationEngine_read
    HostContinuationRunner_record_resume_failure --> ContinuationEngine__run_lock
    HostContinuationRunner_record_resume_failure --> ContinuationEngine__find
    HostContinuationRunner_record_resume_failure --> atomic_write
    HostContinuationRunner_record_resume_failure --> HostContinuationRunner__digest
    HostContinuationRunner_record_resume_failure --> HostContinuationRunner__session_reference
    record_legacy_usage --> _counter_path
    record_legacy_usage --> atomic_write
    read_legacy_usage --> _counter_path
    get_skill_manifest --> get_portable_methods
    _enforce_deploy_integrity --> DeployerBase_validate_deployed_content
    _render_prompt --> DeployerBase_strip_excluded_command_references
    _build_rule_id_to_key --> ContinuationEngine_definition
    _build_rule_id_to_key --> normalize_rule_id
    _build_rule_id_to_filename --> ContinuationEngine_definition
    _render_skill_md --> _rewrite_skills_prefix
    _render_skill_md --> _render_prompt
    _render_skill_md --> _render_prompt
    _render_skill_md --> get_profile
    _load_entry_point_deployers --> StoryRepository_load
    _load_entry_point_deployers --> register_deployer
    _ensure_entry_point_deployers --> _load_entry_point_deployers
    deploy --> _ensure_entry_point_deployers
    deploy --> _deploy_marketplace
    deploy --> check_adapter_compat
    deploy --> deploy
    deploy --> deploy
    deploy --> check_adapter_compat
    deploy --> deploy
    deploy --> deploy
    _deploy_classic --> _migrate_from_scafpy
    _deploy_classic --> validate_config
    _deploy_classic --> activate_pactkit_maintainer_overlay
    _deploy_classic --> get_profile
    _deploy_classic --> _cleanup_legacy_portable_methods
    _deploy_classic --> _deploy_skills
    _deploy_classic --> _cleanup_legacy
    _deploy_classic --> _deploy_rules
    _deploy_classic --> _deploy_guides
    _deploy_classic --> _deploy_claude_md
    _deploy_classic --> _deploy_agents
    _deploy_classic --> _deploy_commands
    _deploy_classic --> _deploy_ci
    _deploy_classic --> _generate_config_if_missing
    _deploy_classic --> atomic_write
    _deploy_classic --> write_deploy_manifest
    _deploy_classic --> _print_mcp_recommendations
    _deploy_classic --> find_pactkit_yaml
    _deploy_classic --> auto_merge_config_file
    _deploy_classic --> load_config
    _deploy_classic --> _generate_project_claude_md
    _deploy_classic --> _update_stack_if_stale
    _deploy_plugin --> _cleanup_legacy_portable_methods
    _deploy_plugin --> _deploy_skills
    _deploy_plugin --> _deploy_claude_md_inline
    _deploy_plugin --> _deploy_agents
    _deploy_plugin --> _deploy_commands
    _deploy_plugin --> _deploy_plugin_json
    _deploy_plugin --> _print_mcp_recommendations
    _deploy_plugin --> get_profile
    _deploy_marketplace --> _deploy_plugin
    _deploy_marketplace --> _deploy_marketplace_json
    _deploy_skills --> get_skill_manifest
    _deploy_skills --> load_previous_hashes
    _deploy_skills --> retire_disabled_skills
    _deploy_skills --> _render_skill_md
    _deploy_skills --> _enforce_deploy_integrity
    _deploy_skills --> preserve_or_write
    _deploy_skills --> atomic_write
    _deploy_skills --> preserve_or_write
    _deploy_skills --> atomic_write
    _cleanup_legacy_portable_methods --> cleanup_unmodified_legacy_skills
    _cleanup_legacy_portable_methods --> _render_skill_md
    _cleanup_legacy_portable_methods --> get_portable_methods
    _deploy_rules --> load_previous_hashes
    _deploy_rules --> preserve_or_write
    _deploy_rules --> normalize_rule_id
    _deploy_rules --> LessonRepository_add
    _deploy_rules --> preserve_or_write
    _deploy_rules --> _render_prompt
    _deploy_rules --> _enforce_deploy_integrity
    _deploy_guides --> load_previous_hashes
    _deploy_guides --> preserve_or_write
    _deploy_guides --> _render_prompt
    _deploy_agents --> retire_disabled_agents
    _deploy_agents --> load_previous_hashes
    _deploy_agents --> _enforce_deploy_integrity
    _deploy_agents --> get_profile
    _deploy_agents --> get_profile
    _deploy_agents --> _render_prompt
    _deploy_agents --> _rewrite_skills_prefix
    _deploy_agents --> preserve_or_write
    _deploy_agents --> atomic_write
    _get_command_rules --> normalize_rule_id
    _build_command_rules_header --> _get_command_rules
    _build_command_rules_header --> _build_rule_id_to_filename
    _deploy_commands --> load_previous_hashes
    _deploy_commands --> cleanup_disabled_command_skills
    _deploy_commands --> _enforce_deploy_integrity
    _deploy_commands --> write_command_manifest
    _deploy_commands --> get_profile
    _deploy_commands --> get_profile
    _deploy_commands --> get_deployable_commands
    _deploy_commands --> _convert_command_frontmatter_opencode
    _deploy_commands --> _build_command_rules_header
    _deploy_commands --> _render_prompt
    _deploy_commands --> _rewrite_skills_prefix
    _deploy_commands --> preserve_or_write
    _deploy_commands --> atomic_write
    _deploy_commands --> _insert_after_frontmatter
    _deploy_commands --> record_deployed_command
    _deploy_ci --> _build_github_workflow
    _deploy_ci --> atomic_write
    _deploy_ci --> _build_gitlab_ci
    _deploy_ci --> atomic_write
    _deploy_ci --> _detect_ghe
    _generate_config_if_missing --> detect_stacks
    _generate_config_if_missing --> resolve_pactkit_yaml_dir
    _generate_config_if_missing --> atomic_write
    _generate_config_if_missing --> find_pactkit_yaml
    _generate_config_if_missing --> generate_default_yaml
    _update_stack_if_stale --> detect_stacks
    _update_stack_if_stale --> update_yaml_stack
    _upsert_venv_managed_block --> atomic_write
    _generate_claude_local_md_if_missing --> atomic_write
    _build_claude_md_managed_content --> detect_venv
    _upsert_claude_md_managed_block --> atomic_write
    _upsert_claude_md_managed_block --> atomic_write
    _upsert_claude_md_managed_block --> atomic_write
    _upsert_claude_md_managed_block --> atomic_write
    _generate_project_claude_md --> _generate_claude_local_md_if_missing
    _generate_project_claude_md --> _build_claude_md_managed_content
    _generate_project_claude_md --> _upsert_claude_md_managed_block
    _generate_project_claude_md --> _upsert_venv_managed_block
    _generate_project_claude_md --> _is_user_modified_claude_md
    _generate_project_claude_md --> atomic_write
    _deploy_plugin_json --> atomic_write
    _deploy_claude_md_inline --> _rewrite_skills_prefix
    _deploy_claude_md_inline --> atomic_write
    _deploy_marketplace_json --> atomic_write
    DeployIntegrityError___init__ --> BoardRenderer___init__
    ClassicDeployer_deploy --> _deploy_classic
    PluginDeployer_deploy --> _deploy_plugin
    _deploy_claude_md --> atomic_write
    _deploy_claude_md --> _is_pactkit_managed_global_md
    _deploy_claude_md --> _propose_claude_md_candidate
    _deploy_claude_md --> atomic_write
    _deploy_claude_md --> _propose_claude_md_candidate
    _deploy_claude_md --> atomic_write
    _propose_claude_md_candidate --> atomic_write
    DeployerBase_validate_deployed_content --> _check_lexical_integrity
    DeployerBase_validate_deployed_content --> _check_semantic_integrity
    DeployerBase_render_prompt --> _render_prompt
    DeployerBase_deploy_skills --> _deploy_skills
    DeployerBase_deploy_rules --> _deploy_rules
    DeployerBase_deploy_agents --> _deploy_agents
    DeployerBase_deploy_commands --> _deploy_commands
    DeployerBase_deploy_guides --> _deploy_guides
    DeployerBase_deploy_ci --> _deploy_ci
    cleanup_disabled_command_skills --> _read_manifest
    write_command_manifest --> atomic_write
    cleanup_unmodified_legacy_skills --> LessonRepository_add