graph TD
    ClassicDeployer_deploy["ClassicDeployer.deploy"]
    DeployerBase_deploy_agents["DeployerBase.deploy_agents"]
    DeployerBase_deploy_ci["DeployerBase.deploy_ci"]
    DeployerBase_deploy_commands["DeployerBase.deploy_commands"]
    DeployerBase_deploy_guides["DeployerBase.deploy_guides"]
    DeployerBase_deploy_rules["DeployerBase.deploy_rules"]
    DeployerBase_deploy_skills["DeployerBase.deploy_skills"]
    DeployerBase_render_prompt["DeployerBase.render_prompt"]
    DeployerBase_strip_excluded_command_references["DeployerBase.strip_excluded_command_references"]
    DeployerBase_validate_deployed_content["DeployerBase.validate_deployed_content"]
    PluginDeployer_deploy["PluginDeployer.deploy"]
    __module__["__module__"]
    _add_fix_flag["_add_fix_flag"]
    _all_config_dirs["_all_config_dirs"]
    _archived["_archived"]
    _board_block["_board_block"]
    _build_claude_md_managed_content["_build_claude_md_managed_content"]
    _build_command_rules_header["_build_command_rules_header"]
    _build_github_workflow["_build_github_workflow"]
    _build_gitlab_ci["_build_gitlab_ci"]
    _build_rule_id_to_filename["_build_rule_id_to_filename"]
    _build_rule_id_to_key["_build_rule_id_to_key"]
    _changed_source_files["_changed_source_files"]
    _check_code_smells["_check_code_smells"]
    _check_dependency_health["_check_dependency_health"]
    _check_docstring_coverage["_check_docstring_coverage"]
    _check_gh_available["_check_gh_available"]
    _check_h1["_check_h1"]
    _check_h2["_check_h2"]
    _check_h3["_check_h3"]
    _check_h4["_check_h4"]
    _check_h5["_check_h5"]
    _check_h6["_check_h6"]
    _check_h7["_check_h7"]
    _check_test_coverage["_check_test_coverage"]
    _classify_coverage["_classify_coverage"]
    _cleanup_legacy["_cleanup_legacy"]
    _cleanup_legacy_commands["_cleanup_legacy_commands"]
    _collect_findings["_collect_findings"]
    _collect_insights["_collect_insights"]
    _collect_insights__dfs["_collect_insights._dfs"]
    _collect_signals["_collect_signals"]
    _compute_hotspots["_compute_hotspots"]
    _compute_layer_level["_compute_layer_level"]
    _compute_score["_compute_score"]
    _convert_command_frontmatter_opencode["_convert_command_frontmatter_opencode"]
    _create_issue["_create_issue"]
    _deploy_agents["_deploy_agents"]
    _deploy_ci["_deploy_ci"]
    _deploy_classic["_deploy_classic"]
    _deploy_claude_md["_deploy_claude_md"]
    _deploy_claude_md_inline["_deploy_claude_md_inline"]
    _deploy_commands["_deploy_commands"]
    _deploy_guides["_deploy_guides"]
    _deploy_marketplace["_deploy_marketplace"]
    _deploy_marketplace_json["_deploy_marketplace_json"]
    _deploy_plugin["_deploy_plugin"]
    _deploy_plugin_json["_deploy_plugin_json"]
    _deploy_rules["_deploy_rules"]
    _deploy_skills["_deploy_skills"]
    _detect_ghe["_detect_ghe"]
    _detect_platform["_detect_platform"]
    _detect_sources["_detect_sources"]
    _ensure_entry_point_deployers["_ensure_entry_point_deployers"]
    _extract_module_path["_extract_module_path"]
    _extract_sprint_contract["_extract_sprint_contract"]
    _find_existing_spec["_find_existing_spec"]
    _fmt_scalar["_fmt_scalar"]
    _generate_claude_local_md_if_missing["_generate_claude_local_md_if_missing"]
    _generate_config_if_missing["_generate_config_if_missing"]
    _generate_continuation["_generate_continuation"]
    _generate_project_claude_md["_generate_project_claude_md"]
    _generate_suggested_tasks["_generate_suggested_tasks"]
    _get_command_rules["_get_command_rules"]
    _get_done_ids["_get_done_ids"]
    _get_git_branches["_get_git_branches"]
    _get_global_version_marker["_get_global_version_marker"]
    _get_issue_tracker_provider["_get_issue_tracker_provider"]
    _get_last_n_entries["_get_last_n_entries"]
    _git["_git"]
    _has_dir_with_files["_has_dir_with_files"]
    _has_production_caller["_has_production_caller"]
    _insert_after_frontmatter["_insert_after_frontmatter"]
    _inside_protected["_inside_protected"]
    _install_argv["_install_argv"]
    _is_doc_only["_is_doc_only"]
    _is_docs_or_tests_only["_is_docs_or_tests_only"]
    _is_duplicate["_is_duplicate"]
    _is_pactkit_managed_global_md["_is_pactkit_managed_global_md"]
    _is_specific["_is_specific"]
    _is_user_modified_claude_md["_is_user_modified_claude_md"]
    _is_version_file["_is_version_file"]
    _jaccard_similarity["_jaccard_similarity"]
    _load_entry_point_deployers["_load_entry_point_deployers"]
    _max_nesting_depth["_max_nesting_depth"]
    _migrate_from_scafpy["_migrate_from_scafpy"]
    _new_public_symbols["_new_public_symbols"]
    _no_external_enabled["_no_external_enabled"]
    _no_git_enabled["_no_git_enabled"]
    _parse_ac_to_reqs["_parse_ac_to_reqs"]
    _parse_active_stories["_parse_active_stories"]
    _parse_board["_parse_board"]
    _parse_coverage_output["_parse_coverage_output"]
    _parse_field_table["_parse_field_table"]
    _parse_item_type["_parse_item_type"]
    _parse_last_lessons["_parse_last_lessons"]
    _parse_recent_completions["_parse_recent_completions"]
    _parse_requirements["_parse_requirements"]
    _parse_touches["_parse_touches"]
    _parse_version["_parse_version"]
    _path_ends_with_ext["_path_ends_with_ext"]
    _path_matches_any["_path_matches_any"]
    _paths_overlap["_paths_overlap"]
    _print_codegraph_sync["_print_codegraph_sync"]
    _print_mcp_recommendations["_print_mcp_recommendations"]
    _pytest_command["_pytest_command"]
    _python_files["_python_files"]
    _read["_read"]
    _read_content["_read_content"]
    _render_prompt["_render_prompt"]
    _render_skill_md["_render_skill_md"]
    _render_stack_line["_render_stack_line"]
    _render_value["_render_value"]
    _repair_table_structure["_repair_table_structure"]
    _resolve_scope["_resolve_scope"]
    _rewrite_skills_prefix["_rewrite_skills_prefix"]
    _rewrite_yaml["_rewrite_yaml"]
    _rotate_if_needed["_rotate_if_needed"]
    _run_pytest_cov["_run_pytest_cov"]
    _sanitize_text["_sanitize_text"]
    _scaffold_audit_spec["_scaffold_audit_spec"]
    _schema_command["_schema_command"]
    _search_issue["_search_issue"]
    _should_refresh_audit["_should_refresh_audit"]
    _spec_status["_spec_status"]
    _strip_code_spans["_strip_code_spans"]
    _suggest_action["_suggest_action"]
    _tool_version["_tool_version"]
    _update_stack_if_stale["_update_stack_if_stale"]
    _upsert_claude_md_managed_block["_upsert_claude_md_managed_block"]
    _upsert_venv_managed_block["_upsert_venv_managed_block"]
    _validate_developer["_validate_developer"]
    _warn_deploy_violations["_warn_deploy_violations"]
    _write_audit_json["_write_audit_json"]
    append_lesson["append_lesson"]
    atomic_write["atomic_write"]
    audit["audit"]
    auto_merge_config_file["auto_merge_config_file"]
    build_report["build_report"]
    check_adapter_skew["check_adapter_skew"]
    check_adapter_skew__major_minor["check_adapter_skew._major_minor"]
    check_archive_honesty["check_archive_honesty"]
    check_config_completeness["check_config_completeness"]
    check_config_copy_drift["check_config_copy_drift"]
    check_config_drift["check_config_drift"]
    check_config_drift__dir_or_file_in_any["check_config_drift._dir_or_file_in_any"]
    check_config_drift__exists_in_any["check_config_drift._exists_in_any"]
    check_coverage["check_coverage"]
    check_dead_imports["check_dead_imports"]
    check_deploy_parity["check_deploy_parity"]
    check_deps["check_deps"]
    check_hld_module_count["check_hld_module_count"]
    check_init_markers["check_init_markers"]
    check_orphaned_specs["check_orphaned_specs"]
    check_pattern_duplication["check_pattern_duplication"]
    check_requirement_evidence["check_requirement_evidence"]
    check_stale_docs["check_stale_docs"]
    check_stale_graphs["check_stale_graphs"]
    check_status_consistency["check_status_consistency"]
    check_version_mismatch["check_version_mismatch"]
    check_wiring["check_wiring"]
    classify_changes["classify_changes"]
    classify_signals["classify_signals"]
    clean_artifacts["clean_artifacts"]
    codegraph_sync["codegraph_sync"]
    collect_changed_files["collect_changed_files"]
    compute_conflicts["compute_conflicts"]
    compute_waves["compute_waves"]
    current_branch["current_branch"]
    decide_test_set["decide_test_set"]
    deploy["deploy"]
    detect_security_scope["detect_security_scope"]
    detect_security_scope__any_content_matches["detect_security_scope._any_content_matches"]
    detect_stack["detect_stack"]
    detect_stacks["detect_stacks"]
    detect_venv["detect_venv"]
    ensure_gate_channel["ensure_gate_channel"]
    existing_config_copies["existing_config_copies"]
    expected_components["expected_components"]
    find_pactkit_yaml["find_pactkit_yaml"]
    format_markdown_table["format_markdown_table"]
    gate_channel["gate_channel"]
    generate_context["generate_context"]
    generate_default_yaml["generate_default_yaml"]
    get_default_config["get_default_config"]
    get_profile["get_profile"]
    get_skill_manifest["get_skill_manifest"]
    hook_entry["hook_entry"]
    install_deps["install_deps"]
    install_git_hook["install_git_hook"]
    install_hook["install_hook"]
    is_environment_format["is_environment_format"]
    issue_sync["issue_sync"]
    lint_context["lint_context"]
    lint_lessons["lint_lessons"]
    lint_testcase["lint_testcase"]
    load_config["load_config"]
    load_story_graph["load_story_graph"]
    main["main"]
    map_to_tests["map_to_tests"]
    next_story_id["next_story_id"]
    pactkit_owned_files["pactkit_owned_files"]
    parse_pytest_summary["parse_pytest_summary"]
    parse_story["parse_story"]
    refresh_test_count["refresh_test_count"]
    register_deployer["register_deployer"]
    render["render"]
    render_check_report["render_check_report"]
    render_config_yaml["render_config_yaml"]
    render_mermaid["render_mermaid"]
    resolve_pactkit_yaml_dir["resolve_pactkit_yaml_dir"]
    run_garden["run_garden"]
    run_gate["run_gate"]
    run_lint["run_lint"]
    run_observe["run_observe"]
    run_pytest["run_pytest"]
    run_visualize_graphs["run_visualize_graphs"]
    run_visualize_single["run_visualize_single"]
    scan_and_replace_tbd["scan_and_replace_tbd"]
    schema_config_report["schema_config_report"]
    sha256_file["sha256_file"]
    should_visualize["should_visualize"]
    strip_frontmatter["strip_frontmatter"]
    sync_config_copies["sync_config_copies"]
    sync_config_copies__pref["sync_config_copies._pref"]
    to_json["to_json"]
    transform["transform"]
    update_spec_status["update_spec_status"]
    update_yaml_stack["update_yaml_stack"]
    validate_config["validate_config"]
    verify_story["verify_story"]
    write_deploy_manifest["write_deploy_manifest"]
    check_deps --> _detect_platform
    check_deps --> _install_argv
    check_deps --> _tool_version
    _no_external_enabled --> load_config
    install_deps --> _no_external_enabled
    install_deps --> _detect_platform
    install_deps --> _install_argv
    install_deps --> check_deps
    classify_changes --> _is_doc_only
    classify_changes --> _is_version_file
    resolve_pactkit_yaml_dir --> is_environment_format
    resolve_pactkit_yaml_dir --> get_profile
    resolve_pactkit_yaml_dir --> get_profile
    sync_config_copies --> existing_config_copies
    sync_config_copies --> sync_config_copies__pref
    check_config_copy_drift --> existing_config_copies
    load_config --> get_default_config
    load_config --> _validate_developer
    load_config --> find_pactkit_yaml
    load_config --> get_default_config
    auto_merge_config_file --> _rewrite_yaml
    update_yaml_stack --> _rewrite_yaml
    _render_value --> _render_value
    _render_value --> _fmt_scalar
    _render_value --> _fmt_scalar
    render_config_yaml --> _render_stack_line
    render_config_yaml --> _render_value
    render_config_yaml --> _fmt_scalar
    _rewrite_yaml --> render_config_yaml
    generate_default_yaml --> _render_stack_line
    schema_config_report --> find_pactkit_yaml
    schema_config_report --> load_config
    schema_config_report --> get_default_config
    _is_duplicate --> _jaccard_similarity
    append_lesson --> _get_last_n_entries
    append_lesson --> _is_duplicate
    append_lesson --> _rotate_if_needed
    append_lesson --> _repair_table_structure
    append_lesson --> _is_specific
    check_init_markers --> find_pactkit_yaml
    check_config_completeness --> find_pactkit_yaml
    check_version_mismatch --> _get_global_version_marker
    check_version_mismatch --> _parse_version
    check_version_mismatch --> _parse_version
    _has_dir_with_files --> _all_config_dirs
    _check_h1 --> _has_dir_with_files
    _check_h1 --> _has_dir_with_files
    _check_h1 --> _compute_layer_level
    _check_h1 --> _all_config_dirs
    _check_h2 --> _compute_layer_level
    _check_h2 --> _all_config_dirs
    _check_h2 --> _all_config_dirs
    _check_h3 --> _all_config_dirs
    _check_h3 --> _compute_layer_level
    _check_h4 --> _all_config_dirs
    _check_h4 --> _compute_layer_level
    _check_h4 --> _all_config_dirs
    _check_h5 --> _all_config_dirs
    _check_h5 --> _all_config_dirs
    _check_h5 --> _compute_layer_level
    _check_h6 --> _all_config_dirs
    _check_h6 --> _all_config_dirs
    _check_h6 --> _compute_layer_level
    _check_h7 --> _compute_layer_level
    _collect_findings --> check_dead_imports
    _collect_insights --> _collect_insights__dfs
    _collect_insights --> _collect_insights__dfs
    _check_code_smells --> _max_nesting_depth
    _max_nesting_depth --> _max_nesting_depth
    _max_nesting_depth --> _max_nesting_depth
    _compute_hotspots --> _check_test_coverage
    _compute_hotspots --> _check_docstring_coverage
    _compute_hotspots --> _check_code_smells
    _compute_hotspots --> _suggest_action
    _generate_suggested_tasks --> _find_existing_spec
    _generate_suggested_tasks --> next_story_id
    _generate_suggested_tasks --> _scaffold_audit_spec
    audit --> _compute_score
    audit --> _write_audit_json
    audit --> _compute_hotspots
    audit --> _check_dependency_health
    audit --> _collect_findings
    audit --> _collect_insights
    audit --> _should_refresh_audit
    audit --> _check_h1
    audit --> _check_h2
    audit --> _check_h3
    audit --> _check_h4
    audit --> _check_h5
    audit --> _check_h6
    audit --> _check_h7
    audit --> load_config
    audit --> _generate_suggested_tasks
    _collect_insights__dfs --> _collect_insights__dfs
    detect_security_scope --> _is_docs_or_tests_only
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> detect_security_scope__any_content_matches
    detect_security_scope --> _read_content
    detect_security_scope --> _path_ends_with_ext
    detect_security_scope --> _path_matches_any
    detect_security_scope --> _path_ends_with_ext
    detect_security_scope --> _path_matches_any
    detect_security_scope --> _path_matches_any
    detect_security_scope --> _path_matches_any
    detect_security_scope --> _path_ends_with_ext
    check_dead_imports --> _resolve_scope
    check_dead_imports --> _python_files
    check_pattern_duplication --> _resolve_scope
    check_pattern_duplication --> _python_files
    run_garden --> check_dead_imports
    run_garden --> check_stale_docs
    run_garden --> check_pattern_duplication
    collect_changed_files --> _git
    current_branch --> _git
    _pytest_command --> detect_venv
    run_pytest --> _pytest_command
    decide_test_set --> current_branch
    decide_test_set --> classify_changes
    decide_test_set --> map_to_tests
    run_gate --> collect_changed_files
    run_gate --> decide_test_set
    run_gate --> run_pytest
    run_gate --> parse_pytest_summary
    hook_entry --> run_gate
    hook_entry --> render
    _no_git_enabled --> load_config
    install_hook --> _no_git_enabled
    install_git_hook --> _no_git_enabled
    gate_channel --> _no_git_enabled
    ensure_gate_channel --> gate_channel
    ensure_gate_channel --> install_hook
    ensure_gate_channel --> install_git_hook
    run_lint --> detect_stack
    run_lint --> find_pactkit_yaml
    run_lint --> _add_fix_flag
    run_lint --> load_config
    expected_components --> is_environment_format
    expected_components --> get_profile
    pactkit_owned_files --> sha256_file
    pactkit_owned_files --> sha256_file
    pactkit_owned_files --> sha256_file
    pactkit_owned_files --> sha256_file
    write_deploy_manifest --> expected_components
    write_deploy_manifest --> pactkit_owned_files
    should_visualize --> detect_stack
    run_visualize_single --> _print_codegraph_sync
    run_visualize_graphs --> _print_codegraph_sync
    _print_codegraph_sync --> codegraph_sync
    _generate_continuation --> _sanitize_text
    _generate_continuation --> _sanitize_text
    _generate_continuation --> _extract_sprint_contract
    _generate_continuation --> _sanitize_text
    generate_context --> _get_git_branches
    generate_context --> _parse_last_lessons
    generate_context --> _generate_continuation
    generate_context --> _parse_board
    generate_context --> _parse_active_stories
    generate_context --> _parse_recent_completions
    run_observe --> _detect_sources
    run_observe --> _collect_signals
    run_observe --> classify_signals
    run_observe --> build_report
    _schema_command --> schema_config_report
    main --> deploy
    main --> deploy
    main --> sync_config_copies
    main --> render_check_report
    main --> check_deps
    main --> _schema_command
    main --> check_init_markers
    main --> ensure_gate_channel
    main --> check_version_mismatch
    main --> load_config
    main --> next_story_id
    main --> clean_artifacts
    main --> classify_changes
    main --> generate_context
    main --> detect_security_scope
    main --> format_markdown_table
    main --> lint_context
    main --> lint_lessons
    main --> lint_testcase
    main --> should_visualize
    main --> run_visualize_single
    main --> run_visualize_graphs
    main --> codegraph_sync
    main --> run_garden
    main --> codegraph_sync
    main --> run_observe
    main --> check_orphaned_specs
    main --> check_config_drift
    main --> check_stale_graphs
    main --> check_hld_module_count
    main --> check_config_copy_drift
    main --> check_deps
    main --> check_deploy_parity
    main --> check_adapter_skew
    main --> scan_and_replace_tbd
    main --> issue_sync
    main --> map_to_tests
    main --> run_lint
    main --> append_lesson
    main --> refresh_test_count
    main --> check_coverage
    main --> update_spec_status
    main --> verify_story
    main --> check_deps
    main --> render
    main --> install_deps
    main --> run_gate
    main --> render_check_report
    main --> hook_entry
    main --> render
    main --> install_git_hook
    main --> detect_stacks
    main --> update_yaml_stack
    main --> load_config
    main --> load_story_graph
    main --> compute_waves
    main --> render
    main --> render_mermaid
    main --> to_json
    scan_and_replace_tbd --> _get_done_ids
    detect_stack --> detect_stacks
    clean_artifacts --> detect_stack
    clean_artifacts --> _inside_protected
    clean_artifacts --> _inside_protected
    parse_story --> _parse_field_table
    parse_story --> _parse_touches
    parse_story --> _parse_field_table
    load_story_graph --> parse_story
    compute_conflicts --> _paths_overlap
    render --> compute_waves
    render --> compute_conflicts
    to_json --> compute_waves
    to_json --> compute_conflicts
    _parse_coverage_output --> _classify_coverage
    check_coverage --> _parse_coverage_output
    check_coverage --> _extract_module_path
    check_coverage --> _run_pytest_cov
    _get_issue_tracker_provider --> find_pactkit_yaml
    issue_sync --> _parse_item_type
    issue_sync --> _get_issue_tracker_provider
    issue_sync --> _search_issue
    issue_sync --> _create_issue
    issue_sync --> _check_gh_available
    map_to_tests --> detect_stack
    _archived --> _read
    check_requirement_evidence --> _read
    check_requirement_evidence --> _read
    check_requirement_evidence --> _parse_ac_to_reqs
    check_requirement_evidence --> _parse_requirements
    check_requirement_evidence --> map_to_tests
    check_archive_honesty --> _strip_code_spans
    check_archive_honesty --> _read
    _changed_source_files --> _git
    _changed_source_files --> _git
    _new_public_symbols --> _git
    _new_public_symbols --> _read
    _new_public_symbols --> _git
    check_wiring --> _changed_source_files
    check_wiring --> _new_public_symbols
    check_wiring --> _has_production_caller
    check_status_consistency --> _read
    check_status_consistency --> _spec_status
    check_status_consistency --> _archived
    verify_story --> _read
    verify_story --> _board_block
    verify_story --> check_requirement_evidence
    verify_story --> check_archive_honesty
    verify_story --> check_wiring
    verify_story --> check_status_consistency
    check_config_drift --> find_pactkit_yaml
    check_config_drift --> check_config_drift__exists_in_any
    check_config_drift --> check_config_drift__dir_or_file_in_any
    check_stale_graphs --> load_config
    check_deploy_parity --> expected_components
    check_deploy_parity --> sha256_file
    check_adapter_skew --> check_adapter_skew__major_minor
    check_adapter_skew --> check_adapter_skew__major_minor
    _warn_deploy_violations --> DeployerBase_validate_deployed_content
    _render_prompt --> DeployerBase_strip_excluded_command_references
    _render_skill_md --> _rewrite_skills_prefix
    _render_skill_md --> _render_prompt
    _render_skill_md --> _render_prompt
    _render_skill_md --> get_profile
    _load_entry_point_deployers --> register_deployer
    _ensure_entry_point_deployers --> _load_entry_point_deployers
    deploy --> _ensure_entry_point_deployers
    deploy --> _deploy_marketplace
    deploy --> deploy
    deploy --> deploy
    _deploy_classic --> _migrate_from_scafpy
    _deploy_classic --> validate_config
    _deploy_classic --> get_profile
    _deploy_classic --> _deploy_skills
    _deploy_classic --> _cleanup_legacy
    _deploy_classic --> _deploy_rules
    _deploy_classic --> _deploy_guides
    _deploy_classic --> _deploy_claude_md
    _deploy_classic --> _deploy_agents
    _deploy_classic --> _cleanup_legacy_commands
    _deploy_classic --> _deploy_commands
    _deploy_classic --> _deploy_ci
    _deploy_classic --> _generate_config_if_missing
    _deploy_classic --> atomic_write
    _deploy_classic --> write_deploy_manifest
    _deploy_classic --> _print_mcp_recommendations
    _deploy_classic --> find_pactkit_yaml
    _deploy_classic --> auto_merge_config_file
    _deploy_classic --> load_config
    _deploy_classic --> _generate_project_claude_md
    _deploy_classic --> _update_stack_if_stale
    _deploy_plugin --> _deploy_skills
    _deploy_plugin --> _deploy_claude_md_inline
    _deploy_plugin --> _deploy_agents
    _deploy_plugin --> _deploy_commands
    _deploy_plugin --> _deploy_plugin_json
    _deploy_plugin --> _print_mcp_recommendations
    _deploy_marketplace --> _deploy_plugin
    _deploy_marketplace --> _deploy_marketplace_json
    _deploy_skills --> get_skill_manifest
    _deploy_skills --> _render_skill_md
    _deploy_skills --> atomic_write
    _deploy_skills --> _warn_deploy_violations
    _deploy_skills --> atomic_write
    _deploy_rules --> _build_rule_id_to_key
    _deploy_rules --> atomic_write
    _deploy_rules --> _render_prompt
    _deploy_rules --> _warn_deploy_violations
    _deploy_guides --> atomic_write
    _deploy_guides --> _render_prompt
    _deploy_claude_md --> atomic_write
    _deploy_claude_md --> _is_pactkit_managed_global_md
    _deploy_claude_md --> atomic_write
    _deploy_claude_md --> atomic_write
    _deploy_agents --> _warn_deploy_violations
    _deploy_agents --> atomic_write
    _deploy_agents --> get_profile
    _deploy_agents --> get_profile
    _deploy_agents --> _render_prompt
    _deploy_agents --> _rewrite_skills_prefix
    _build_command_rules_header --> _get_command_rules
    _build_command_rules_header --> _build_rule_id_to_filename
    _deploy_commands --> _warn_deploy_violations
    _deploy_commands --> get_profile
    _deploy_commands --> get_profile
    _deploy_commands --> _convert_command_frontmatter_opencode
    _deploy_commands --> _build_command_rules_header
    _deploy_commands --> _render_prompt
    _deploy_commands --> _rewrite_skills_prefix
    _deploy_commands --> atomic_write
    _deploy_commands --> atomic_write
    _deploy_commands --> _insert_after_frontmatter
    _deploy_ci --> _build_github_workflow
    _deploy_ci --> atomic_write
    _deploy_ci --> _build_gitlab_ci
    _deploy_ci --> atomic_write
    _deploy_ci --> _detect_ghe
    _generate_config_if_missing --> detect_stacks
    _generate_config_if_missing --> resolve_pactkit_yaml_dir
    _generate_config_if_missing --> atomic_write
    _generate_config_if_missing --> find_pactkit_yaml
    _generate_config_if_missing --> generate_default_yaml
    _update_stack_if_stale --> detect_stacks
    _update_stack_if_stale --> update_yaml_stack
    _upsert_venv_managed_block --> atomic_write
    _generate_claude_local_md_if_missing --> atomic_write
    _build_claude_md_managed_content --> detect_venv
    _upsert_claude_md_managed_block --> atomic_write
    _upsert_claude_md_managed_block --> atomic_write
    _upsert_claude_md_managed_block --> atomic_write
    _upsert_claude_md_managed_block --> atomic_write
    _generate_project_claude_md --> _generate_claude_local_md_if_missing
    _generate_project_claude_md --> _build_claude_md_managed_content
    _generate_project_claude_md --> _upsert_claude_md_managed_block
    _generate_project_claude_md --> _upsert_venv_managed_block
    _generate_project_claude_md --> _is_user_modified_claude_md
    _generate_project_claude_md --> atomic_write
    _deploy_plugin_json --> atomic_write
    _deploy_claude_md_inline --> _build_rule_id_to_key
    _deploy_claude_md_inline --> _rewrite_skills_prefix
    _deploy_claude_md_inline --> atomic_write
    _deploy_marketplace_json --> atomic_write
    ClassicDeployer_deploy --> _deploy_classic
    PluginDeployer_deploy --> _deploy_plugin
    __module__ --> _generate_project_claude_md
    transform --> strip_frontmatter
    DeployerBase_render_prompt --> _render_prompt
    DeployerBase_deploy_skills --> _deploy_skills
    DeployerBase_deploy_rules --> _deploy_rules
    DeployerBase_deploy_agents --> _deploy_agents
    DeployerBase_deploy_commands --> _deploy_commands
    DeployerBase_deploy_guides --> _deploy_guides
    DeployerBase_deploy_ci --> _deploy_ci