graph LR
    subgraph wave1[Wave 1]
        BUG-001
        BUG-003
        BUG-004
        BUG-005
        BUG-006
        BUG-007
        BUG-008
        BUG-009
        BUG-010
        BUG-011
        BUG-012
        BUG-013
        BUG-014
        BUG-015
        BUG-016
        BUG-017
        BUG-018
        BUG-019
        BUG-020
        BUG-021
        BUG-022
        BUG-023
        BUG-024
        BUG-025
        BUG-026
        BUG-027
        BUG-028
        BUG-029
        BUG-030
        BUG-031
        BUG-032
        BUG-034
        BUG-035
        BUG-slim-001
        BUG-slim-002
        BUG-slim-003
        BUG-slim-004
        BUG-slim-005
        BUG-slim-006
        BUG-slim-107
        HOTFIX-slim-023
        HOTFIX-slim-049
        HOTFIX-slim-052
        HOTFIX-slim-067
        HOTFIX-slim-085
        HOTFIX-slim-087
        HOTFIX-slim-096
        HOTFIX-slim-099
        HOTFIX-slim-107
        HOTFIX-slim-122
        HOTFIX-slim-126
        HOTFIX-slim-130
        HOTFIX-slim-131
        STORY-001
        STORY-002
        STORY-003
        STORY-004
        STORY-005
        STORY-006
        STORY-007
        STORY-008
        STORY-009
        STORY-010
        STORY-011
        STORY-012
        STORY-013
        STORY-014
        STORY-015
        STORY-016
        STORY-017
        STORY-019
        STORY-020
        STORY-021
        STORY-022
        STORY-023
        STORY-024
        STORY-025
        STORY-026
        STORY-027
        STORY-028
        STORY-029
        STORY-030
        STORY-031
        STORY-032
        STORY-033
        STORY-034
        STORY-035
        STORY-036
        STORY-037
        STORY-038
        STORY-039
        STORY-040
        STORY-042
        STORY-043
        STORY-044
        STORY-045
        STORY-046
        STORY-047
        STORY-048
        STORY-049
        STORY-050
        STORY-051
        STORY-052
        STORY-053
        STORY-054
        STORY-055
        STORY-056
        STORY-057
        STORY-058
        STORY-059
        STORY-060
        STORY-061
        STORY-062
        STORY-063
        STORY-064
        STORY-065
        STORY-069
        STORY-070
        STORY-071
        STORY-072
        STORY-073
        STORY-slim-001
        STORY-slim-005
        STORY-slim-006
        STORY-slim-007
        STORY-slim-009
        STORY-slim-011
        STORY-slim-012
        STORY-slim-013
        STORY-slim-014
        STORY-slim-015
        STORY-slim-016
        STORY-slim-017
        STORY-slim-086
        STORY-slim-094
        STORY-slim-108
        STORY-slim-109
        STORY-slim-110
        STORY-slim-111
        STORY-slim-112
        STORY-slim-115
        STORY-slim-116
        STORY-slim-118
        STORY-slim-119
        STORY-slim-128
        STORY-slim-143
    end
