"""Ownership manifest for selectively deployed PactKit command skills."""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path
from typing import Iterable

from pactkit.utils import atomic_write

_MANIFEST_FILE = ".pactkit-command-manifest.json"
_MANIFEST_VERSION = 2
# v1 manifests carry only the ``commands`` table; v2 adds ``references``.
# Both remain readable so an in-place upgrade never loses command ownership
# (STORY-slim-20260827fc9de5542ad7 R1).
_READABLE_VERSIONS = (1, 2)
_DIGEST = re.compile(r"[0-9a-f]{64}")


def cleanup_disabled_command_skills(
    skills_dir: Path, enabled_commands: Iterable[str], known_commands: Iterable[str],
    *, manifest_entries: dict[str, str] | None = None,
) -> dict[str, str]:
    """Remove only unchanged command directories proven PactKit-owned.

    A command name is not an ownership claim.  The manifest binds each command
    to the digest written by PactKit.  A modified or untracked entry is retained
    and no longer managed.
    """
    manifest = (
        _read_manifest(skills_dir, set(known_commands))
        if manifest_entries is None
        else dict(manifest_entries)
    )
    enabled = set(enabled_commands)
    retained: dict[str, str] = {}
    for name, expected_digest in manifest.items():
        skill = skills_dir / name / "SKILL.md"
        if name in enabled:
            retained[name] = expected_digest
            continue
        try:
            actual_digest = hashlib.sha256(skill.read_bytes()).hexdigest()
        except OSError:
            continue
        if actual_digest == expected_digest:
            # The digest proves ownership of SKILL.md, not of every file a
            # user may have placed beside it.  Remove the whole directory
            # only when it contains that one managed file; otherwise retire
            # just the command entry and leave user additions intact.
            try:
                files = [path for path in skill.parent.rglob("*") if path.is_file()]
            except OSError:
                continue
            if files == [skill]:
                shutil.rmtree(skill.parent)
            else:
                skill.unlink()
    return retained


def record_deployed_command(entries: dict[str, str], name: str, skill_file: Path) -> None:
    """Record the digest produced by one successful PactKit write."""
    entries[name] = hashlib.sha256(skill_file.read_bytes()).hexdigest()


def record_deployed_reference(
    references: dict[str, str], relative_path: str, reference_file: Path,
) -> None:
    """Record the digest of one successfully written command reference.

    The digest is read back from the file the deployer just wrote — the same
    "record what actually landed" semantics as ``record_deployed_command``.
    Files preserved as ``.pactkit-new`` candidates are never recorded: a
    user-modified reference stays outside the ownership ledger so a later
    cleanup cannot delete it (STORY-slim-20260827fc9de5542ad7 R2).
    """
    references[relative_path] = hashlib.sha256(reference_file.read_bytes()).hexdigest()


def write_command_manifest(
    skills_dir: Path, entries: dict[str, str],
    references: dict[str, str] | None = None,
) -> None:
    """Persist the complete ownership projection atomically."""
    atomic_write(
        skills_dir / _MANIFEST_FILE,
        json.dumps(
            {
                "version": _MANIFEST_VERSION,
                "commands": dict(sorted(entries.items())),
                "references": dict(sorted((references or {}).items())),
            },
            indent=2, ensure_ascii=False,
        ) + "\n",
    )


def cleanup_unmodified_legacy_skills(
    skills_dir: Path, expected_contents: dict[str, str],
) -> set[str]:
    """Remove obsolete skills only when they are provably untouched.

    Legacy portable methods predate the command ownership manifest.  Their
    directory name is therefore not evidence that PactKit owns them.  A
    directory is removed only when it contains exactly one ``SKILL.md`` whose
    bytes match the artifact generated by the prior release.  User edits,
    additional files, and unrecognised directories are always retained.
    """
    removed: set[str] = set()
    for name, expected_content in expected_contents.items():
        skill_dir = skills_dir / name
        skill_file = skill_dir / "SKILL.md"
        if not skill_dir.is_dir() or not skill_file.is_file():
            continue
        try:
            files = [path for path in skill_dir.rglob("*") if path.is_file()]
            if files != [skill_file]:
                continue
            if skill_file.read_bytes() != expected_content.encode("utf-8"):
                continue
        except OSError:
            continue
        shutil.rmtree(skill_dir)
        removed.add(name)
    return removed


def _read_manifest(skills_dir: Path, known_commands: set[str]) -> dict[str, str]:
    path = skills_dir / _MANIFEST_FILE
    if not path.is_file():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    # A user-owned manifest is an input boundary.  Valid JSON may still be a
    # list, scalar, or null; treat all of those as an empty ownership record so
    # deployment can finish and atomically write a fresh manifest.
    if not isinstance(payload, dict):
        return {}
    entries = payload.get("commands")
    if payload.get("version") not in _READABLE_VERSIONS or not isinstance(entries, dict):
        return {}
    return {
        name: digest for name, digest in entries.items()
        if name in known_commands and isinstance(digest, str) and _DIGEST.fullmatch(digest)
    }


def read_command_references(skills_dir: Path) -> dict[str, str]:
    """Read the v2 reference-digest table used as deletion proof.

    Missing file, corrupt JSON, wrong shape, or a v1 manifest (no
    ``references`` section) all degrade to an empty table — the caller then
    conservatively preserves everything (STORY-slim-20260827fc9de5542ad7 R4).
    """
    path = skills_dir / _MANIFEST_FILE
    if not path.is_file():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(payload, dict) or payload.get("version") != _MANIFEST_VERSION:
        return {}
    references = payload.get("references")
    if not isinstance(references, dict):
        return {}
    return {
        relative: digest for relative, digest in references.items()
        if isinstance(relative, str) and isinstance(digest, str) and _DIGEST.fullmatch(digest)
    }
